## Phase 3 - Modelling

### Set up Directories

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

BASE_DIR = Path(r"x:\My Files\Python\Sports Analytics Projects\Hockey\HALO")
DATA_DIR = BASE_DIR / "HALO Hackathon Data"
INUPT_DIR = BASE_DIR / "Tensor-Ready Data"
OUTPUT_DIR = BASE_DIR / "Tensor-Ready Data" / "Final Datasets"


print(f"BASE_DIR: {BASE_DIR}")
print(f"DATA_DIR: {DATA_DIR}")
print(f"OUTPUT_DIR: {OUTPUT_DIR}")
print(f"INUPT_DIR: {INUPT_DIR}")

BASE_DIR: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO
DATA_DIR: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\HALO Hackathon Data
OUTPUT_DIR: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets
INUPT_DIR: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data


### Preview Events with Stints and Tracking Data
- Load in data and display head to get current state

In [2]:
events_tracking_path = INUPT_DIR / "events_with_tracking_features.parquet"
df_events = pd.read_parquet(events_tracking_path)
print(f"Loaded {len(df_events):,} events with tracking features")

Loaded 1,658,796 events with tracking features


In [3]:
df_events.head(10)

,game_id,period,period_time,game_stint,sequence_id,player_id,team_id,opp_team_id,event_type,outcome,...,opp_5_mask,opp_6_rel_x,opp_6_rel_y,opp_6_distance,opp_6_vx_std,opp_6_vy_std,opp_6_mask,actor_is_imputed,distance_to_net_actor,angle_to_net_actor
0,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.00,1.0,1,8cdcb61e-d733-bde6-a101-ef3140e48149,6cac12e2-0546-2c1a-689f-ab26d8a6355a,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,faceoff,failed,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,89.204631,-0.008470
1,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.00,1.0,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,faceoff,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,88.801783,0.008508
2,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.07,1.0,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,89.816045,-0.014000
3,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.13,1.0,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,89.308312,-0.009472
4,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.20,1.0,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,97.607346,-0.215981
5,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.47,1.0,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,98.166091,-0.240550
6,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,3.37,1.0,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,68.422245,-0.309996
7,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,4.43,1.0,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,52.443228,-0.518571
8,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,7.13,1.0,1,0f052c34-6cd2-f4fd-a861-d9051a8e86e4,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,failed,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,20.624672,1.728390
9,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.27,1.0,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,6cac12e2-0546-2c1a-689f-ab26d8a6355a,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,185.739197,-0.071818


In [4]:
# Explore column structure + enforce strict Phase 2 -> Phase 3 schema contract
print(f"Total columns: {len(df_events.columns)}")
print(f"\nColumn groups:")

# Event-level columns
event_cols = [c for c in df_events.columns if not any(x in c for x in ['actor_', 'tm_', 'opp_'])]
print(f"  Event columns: {len(event_cols)}")

# Tracking columns
actor_cols = [c for c in df_events.columns if c.startswith('actor_')]
tm_cols = [c for c in df_events.columns if c.startswith('tm_')]
opp_cols = [c for c in df_events.columns if c.startswith('opp_')]
print(f"  Actor columns: {len(actor_cols)}")
print(f"  Teammate columns: {len(tm_cols)}")
print(f"  Opponent columns: {len(opp_cols)}")

# ------------------------------------------------------------------
# HARD SCHEMA GATE (required for dynamic-horizon target engineering)
# ------------------------------------------------------------------
required_phase2_cols = [
    'game_id', 'period', 'period_time', 'sequence_id',
    'event_type', 'team_id', 'player_id', 'detail',
    'sl_event_id', 'game_time_sec', 'is_boundary_event', 'is_end_of_period'
]

missing_required = [col for col in required_phase2_cols if col not in df_events.columns]
if missing_required:
    raise KeyError(
        "Phase 3 hard-fail: Phase 2 continuity contract missing required columns: "
        f"{missing_required}. Re-run updated Phase 2 pipeline before Phase 3."
    )

print("\n✓ Phase 2 -> Phase 3 schema gate passed")

# Reception contract check (must be retained from Phase 1/2 policy)
reception_count = int((df_events['event_type'] == 'reception').sum())
print(f"✓ Reception events retained: {reception_count:,}")
if reception_count == 0:
    raise ValueError(
        "Phase 3 hard-fail: no 'reception' events found, but Phase 1/2 policy requires retention. "
        "Check upstream filtering/version mismatch."
    )

print(f"\nEvent-level columns:")
for col in event_cols:
    print(f"  - {col}")

Total columns: 118

Column groups:
  Event columns: 45
  Actor columns: 6
  Teammate columns: 30
  Opponent columns: 37

✓ Phase 2 -> Phase 3 schema gate passed
✓ Reception events retained: 304,903

Event-level columns:
  - game_id
  - period
  - period_time
  - game_stint
  - sequence_id
  - player_id
  - team_id
  - event_type
  - outcome
  - flags
  - flags_clean
  - description
  - description_clean
  - detail
  - x
  - y
  - x_adj
  - y_adj
  - has_tracking_data
  - event_player_tracked
  - dest_x_adj
  - dest_y_adj
  - sl_event_id
  - sl_xg_all_shots
  - embedding_text_clean
  - period_time_start
  - period_time_end
  - n_home_skaters
  - n_away_skaters
  - is_home_net_empty
  - is_away_net_empty
  - home_score
  - away_score
  - score_differential_home
  - score_differential_away
  - sequence_event_id
  - game_event_id
  - is_boundary_event
  - is_end_of_period
  - game_time_sec
  - distance_to_net_event
  - angle_to_net_event
  - tracking_key
  - distance_to_net_actor
  - angle

In [5]:
# Load games data
games_path = DATA_DIR / "games.parquet"
df_games = pd.read_parquet(games_path)

print(f"Loaded {len(df_games):,} games")
print(f"\nGames columns: {df_games.columns.tolist()}")
print(f"\nSample game:")
print(df_games.head(1).T)

# Create home team lookup
home_team_lookup = df_games.set_index('game_id')['home_team_id'].to_dict()
print(f"\nCreated home team lookup for {len(home_team_lookup):,} games")

Loaded 480 games

Games columns: ['game_id', 'game_date', 'league', 'season', 'home_team', 'away_team', 'home_team_id', 'away_team_id', 'home_score', 'away_score', 'game_outcome', 'home_start_net']

Sample game:
                                                   0
game_id         0f51a5c7-6d54-1917-d4a5-9e83a0b4a1ea
game_date                                 2024-04-20
league                                           AHL
season                                          2023
home_team                                        CHI
away_team                                         IA
home_team_id    2fddd6bd-144f-ca64-90e3-8d36f96c8b28
away_team_id    50030ea0-2c9b-66e2-a36c-bab16b79492c
home_score                                         2
away_score                                         3
game_outcome                                away_win
home_start_net                                 pos_x

Created home team lookup for 480 games


### Add Possession-Relative Features

Transform features to be relative to the possessing team (team_id), not fixed home/away perspective.

In [6]:
# Add home team identification
df_events['home_team_id'] = df_events['game_id'].map(home_team_lookup)

# Binary flag: Is the possessing team (team_id) playing at home?
df_events['home_team_poss'] = (df_events['team_id'] == df_events['home_team_id']).astype(int)

print(f"Added home_team_poss flag:")
print(f"  Home possession: {df_events['home_team_poss'].sum():,} events ({df_events['home_team_poss'].mean()*100:.1f}%)")
print(f"  Away possession: {(1-df_events['home_team_poss']).sum():,} events ({(1-df_events['home_team_poss']).mean()*100:.1f}%)")

# Calculate period_time_remaining (20 min periods = 1200 seconds)
df_events['period_time_remaining'] = 1200 - df_events['period_time']

#clip to 0-1200 range to avoid any potential outliers (e.g. due to tracking errors)
df_events['period_time_remaining'] = df_events['period_time_remaining'].clip(0, 1200)

print(f"\n✓ Calculated period_time_remaining")
print(f"  Range: [{df_events['period_time_remaining'].min():.1f}, {df_events['period_time_remaining'].max():.1f}]")

# Transform score differential to possession-relative
# If team_id is home: use score_differential_home
# If team_id is away: use score_differential_away (which is negative of home)
df_events['score_differential_poss'] = np.where(
    df_events['home_team_poss'] == 1,
    df_events['score_differential_home'],
    df_events['score_differential_away']
)

print(f"\n✓ Calculated score_differential_poss (relative to possessing team)")
print(f"  Range: [{df_events['score_differential_poss'].min()}, {df_events['score_differential_poss'].max()}]")
print(f"  Mean: {df_events['score_differential_poss'].mean():.3f}")

# Transform skater counts to possession-relative
df_events['n_skaters_poss'] = np.where(
    df_events['home_team_poss'] == 1,
    df_events['n_home_skaters'],
    df_events['n_away_skaters']
)

df_events['n_skaters_def'] = np.where(
    df_events['home_team_poss'] == 1,
    df_events['n_away_skaters'],
    df_events['n_home_skaters']
)

print(f"\n✓ Calculated n_skaters_poss and n_skaters_def")
print(f"  Possession skaters - Mean: {df_events['n_skaters_poss'].mean():.2f}, Range: [{df_events['n_skaters_poss'].min()}, {df_events['n_skaters_poss'].max()}]")
print(f"  Defending skaters - Mean: {df_events['n_skaters_def'].mean():.2f}, Range: [{df_events['n_skaters_def'].min()}, {df_events['n_skaters_def'].max()}]")

# Transform net empty flags to possession-relative
df_events['net_empty_poss'] = np.where(
    df_events['home_team_poss'] == 1,
    df_events['is_home_net_empty'],
    df_events['is_away_net_empty']
).astype(int)

df_events['net_empty_def'] = np.where(
    df_events['home_team_poss'] == 1,
    df_events['is_away_net_empty'],
    df_events['is_home_net_empty']
).astype(int)

print(f"\n✓ Calculated net_empty_poss and net_empty_def")
print(f"  Possessing net empty: {df_events['net_empty_poss'].sum():,} events ({df_events['net_empty_poss'].mean()*100:.2f}%)")
print(f"  Defending net empty: {df_events['net_empty_def'].sum():,} events ({df_events['net_empty_def'].mean()*100:.2f}%)")

print(f"\n{'='*80}")
print(f"POSSESSION-RELATIVE TRANSFORMATIONS COMPLETE")
print(f"{'='*80}")
print(f"\nSample of transformed features:")
sample_cols = ['team_id', 'home_team_id', 'home_team_poss', 
               'score_differential_poss', 'n_skaters_poss', 'n_skaters_def',
               'net_empty_poss', 'net_empty_def', 'period_time_remaining']
print(df_events[sample_cols].head(10))

Added home_team_poss flag:
  Home possession: 823,376 events (49.6%)
  Away possession: 835,420 events (50.4%)

✓ Calculated period_time_remaining
  Range: [0.0, 1200.0]

✓ Calculated score_differential_poss (relative to possessing team)
  Range: [-8, 8]
  Mean: -0.034

✓ Calculated n_skaters_poss and n_skaters_def
  Possession skaters - Mean: 4.92, Range: [3, 6]
  Defending skaters - Mean: 4.83, Range: [3, 6]

✓ Calculated net_empty_poss and net_empty_def
  Possessing net empty: 23,847 events (1.44%)
  Defending net empty: 11,457 events (0.69%)

POSSESSION-RELATIVE TRANSFORMATIONS COMPLETE

Sample of transformed features:
                                team_id                          home_team_id  \
0  6cac12e2-0546-2c1a-689f-ab26d8a6355a  6cac12e2-0546-2c1a-689f-ab26d8a6355a   
1  d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019  6cac12e2-0546-2c1a-689f-ab26d8a6355a   
2  d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019  6cac12e2-0546-2c1a-689f-ab26d8a6355a   
3  d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019  6cac

### Define Feature Groups for Model

Based on the 4-branch architecture in README:
- **Categorical Features**: event_type, outcome, period (will be integer-embedded separately in model)
- **Text Features**: embedding_text_clean (cleaned, leakage-checked text to be pre-embedded to 384-dim)
- **Continuous Event Features**: Raw coordinates/angles + Possession-relative features (score_differential_poss, n_skaters_poss/def, period_time_remaining)
- **Binary Features**: home_team_poss, net_empty_poss, net_empty_def, is_eos (EOS token for sequence terminators)
- **Tracking Features**: 72 dimensions (actor:6 + teammates:30 + opponents:36)

Note: Features will be transformed to possession-relative perspective (relative to team_id, not fixed home/away).

In [ ]:
# Define feature groups for final dataset
# These will be created through transformations below

# Categorical features (will be integer-embedded separately)
CATEGORICAL_FEATURES = ['event_type', 'outcome', 'period']

# Text features (will be pre-embedded with SentenceTransformer)
TEXT_FEATURES = ['embedding_text_clean']

# Continuous event features (possession-relative, to be calculated)
CONTINUOUS_EVENT_FEATURES_RAW = [
    'x',
    'y',
    'x_adj', 
    'y_adj', 
    'dest_x_adj',
    'dest_y_adj',
    'period_time',
    'distance_to_net_event', 
    'angle_to_net_event'
]

CONTINUOUS_POSSESSION_FEATURES = [
    'period_time_remaining',  # 1200 - period_time
    'score_differential_poss',  # Relative to possessing team
    'n_skaters_poss',  # Number of skaters for possessing team
    'n_skaters_def'  # Number of skaters for defending team
]

CONTINUOUS_EVENT_FEATURES = CONTINUOUS_EVENT_FEATURES_RAW + CONTINUOUS_POSSESSION_FEATURES

# Binary features (possession-relative, to be calculated)
BINARY_EVENT_FEATURES = [
    'net_empty_poss',  # Is possessing team's net empty
    'net_empty_def',  # Is defending team's net empty
    'home_team_poss'  # Is possessing team playing at home
]

# Tracking features (72 dimensions) - already exist
# Actor: 6 features
ACTOR_FEATURES = [
    'actor_rel_x', 'actor_rel_y', 'actor_vx_std', 'actor_vy_std', 
    'actor_mask', 'actor_is_imputed'
]

# Teammates: 5 players × 6 features = 30
TEAMMATE_FEATURES = []
for i in range(1, 6):
    TEAMMATE_FEATURES.extend([
        f'tm_{i}_rel_x', f'tm_{i}_rel_y', f'tm_{i}_vx_std', f'tm_{i}_vy_std',
        f'tm_{i}_distance', f'tm_{i}_mask'
    ])

# Opponents: 6 players × 6 features = 36
OPPONENT_FEATURES = []
for i in range(1, 7):
    OPPONENT_FEATURES.extend([
        f'opp_{i}_rel_x', f'opp_{i}_rel_y', f'opp_{i}_vx_std', f'opp_{i}_vy_std',
        f'opp_{i}_distance', f'opp_{i}_mask'
    ])

# All tracking features
TRACKING_FEATURES = ACTOR_FEATURES + TEAMMATE_FEATURES + OPPONENT_FEATURES

print(f"Feature group sizes (after transformations will be applied):")
print(f"  Categorical: {len(CATEGORICAL_FEATURES)}")
print(f"  Text: {len(TEXT_FEATURES)} (will be SentenceTransformer embedded)")
print(f"  Continuous Event: {len(CONTINUOUS_EVENT_FEATURES)}")
print(f"    - Raw coordinates/angles: {len(CONTINUOUS_EVENT_FEATURES_RAW)}")
print(f"    - Possession-relative: {len(CONTINUOUS_POSSESSION_FEATURES)}")
print(f"  Binary: {len(BINARY_EVENT_FEATURES)}")
print(f"  Tracking Features: {len(TRACKING_FEATURES)}")
print(f"    - Actor: {len(ACTOR_FEATURES)}")
print(f"    - Teammates: {len(TEAMMATE_FEATURES)}")
print(f"    - Opponents: {len(OPPONENT_FEATURES)}")

# Verify raw columns exist now
print(f"\nVerifying currently available columns...")
required_now = CATEGORICAL_FEATURES + CONTINUOUS_EVENT_FEATURES_RAW + TEXT_FEATURES + TRACKING_FEATURES
missing_cols = [col for col in required_now if col not in df_events.columns]

if missing_cols:
    print(f"❌ Missing columns: {missing_cols}")
else:
    print(f"✓ All required raw columns present")
    print(f"  (Possession-relative features will be calculated next)")

Feature group sizes (after transformations will be applied):
  Categorical: 3
  Text: 1 (will be SentenceTransformer embedded)
  Continuous Event: 11
    - Raw coordinates/angles: 7
    - Possession-relative: 4
  Binary: 3
  Tracking Features: 72
    - Actor: 6
    - Teammates: 30
    - Opponents: 36

Verifying currently available columns...
✓ All required raw columns present
  (Possession-relative features will be calculated next)


### Generate Text Embeddings with SentenceTransformer

Pre-compute 384-dim embeddings from `embedding_text_clean` using all-MiniLM-L6-v2.
Strategy: Encode unique cleaned text values, then map back to all events using `text_embedding_idx`.

In [8]:
import torch
import intel_extension_for_pytorch as ipex

print(f"PyTorch Version: {torch.__version__}")
print(f"IPEX Version: {ipex.__version__}")
print(f"XPU Available: {torch.xpu.is_available()}")

if torch.xpu.is_available():
    device_name = torch.xpu.get_device_name(0)
    print(f"Detected GPU: {device_name}")
    
    # Simple check: Move a tensor to the B580 and do math
    a = torch.ones(5, 5).to("xpu")
    b = torch.ones(5, 5).to("xpu")
    c = a + b
    print("\nComputation on B580 successful!")
    print(c)
else:
    print("\nB580 not detected. Ensure 'setvars.bat' ran successfully.")

PyTorch Version: 2.6.0+xpu
IPEX Version: 2.6.10+xpu
XPU Available: True
Detected GPU: Intel(R) Arc(TM) B580 Graphics

Computation on B580 successful!
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], device='xpu:0')


In [9]:
# Preview embedding source text from embedding_text_clean where event_type is 'shot' (primary event for xG modeling)
if 'embedding_text_clean' not in df_events.columns:
    raise KeyError("Missing required column: embedding_text_clean")

# Strip the leaky outcome words but keep the shot qualities
df_events['embedding_text_clean'] = df_events['embedding_text_clean'].str.replace(r' for (missed|blocked) ;', ' for ;', regex=True)

embedding_source = df_events[df_events['event_type'] == 'shot']['embedding_text_clean'].dropna().astype(str).str.strip()
embedding_source = embedding_source[embedding_source != '']


#get unique non-empty text values from embedding_text_clean for shot events (primary event for xG modeling)
print(f"Found {len(embedding_source):,} non-empty rows in 'embedding_text_clean'")
print(f"Unique non-empty text values: {embedding_source.nunique():,}")
print("Sample embedding_text_clean values:")
for text in embedding_source.drop_duplicates().head(50):
    print(f"  - {text}")
    
#Save to csv for reference
embedding_source.drop_duplicates().to_csv(OUTPUT_DIR / "embedding_text_clean_shots_unique.csv", index=False)

Found 53,964 non-empty rows in 'embedding_text_clean'
Unique non-empty text values: 1,467
Sample embedding_text_clean values:
  - slot shot for ; wristshot, highright
  - outside shot for ; wristshot, lowright
  - outside shot for ; wristshot, lowleft
  - outside shot for ; wristshot, quickrelease, seam, westeast, lowright
  - outside shot for ; wristshot
  - outside shot for ; snapshot, lowleft
  - outside shot for ; wristshot, quickrelease, lowright
  - outside shot for ; slapshot, quickrelease
  - slot shot for ; snapshot, quickrelease, seam, eastwest, lowleft
  - outside shot for ; wristshot, quickrelease, eastwest, lowleft
  - outside shot for ; wristshot, quickrelease, seam, eastwest, lowhigh, lowleft
  - outside shot for ; wristshot, quickrelease, eastside, lowright
  - outside shot for ; screened, wristshot, quickrelease, westside, lowright
  - outside shot for ; wristshot, quickrelease, eastside
  - slot shot for ; snapshot, quickrelease, eastside
  - slot shot for ; snapshot,

In [10]:
import re

# Install sentence-transformers if not available
try:
    from sentence_transformers import SentenceTransformer
    print("✓ sentence-transformers already installed")
except ImportError:
    print("Installing sentence-transformers...")
    import subprocess
    subprocess.check_call(['pip', 'install', 'sentence-transformers'])
    from sentence_transformers import SentenceTransformer
    print("✓ sentence-transformers installed")

import torch
try:
    import intel_extension_for_pytorch as ipex
    print(f"✓ Intel Extension for PyTorch available (version: {ipex.__version__})")
except ImportError:
    print("⚠ Intel Extension not found (install 'intel_extension_for_pytorch' for Arc GPU acceleration)")

if 'embedding_text_clean' not in df_events.columns:
    raise KeyError("Missing required column: embedding_text_clean")

# Double-check for leakage before embedding
leak_regex = re.compile(
    r"\bgoal\b|\bgoals\b|\bon\s*net\b|\bonnet\b|\bwith\s*goal\b|\bwith\s*shot\s*on\s*net(?:\s*whistle)?\bwith*\b",
    flags=re.IGNORECASE
)
blocked_compact_tokens = {'withgoal', 'withshotonnet', 'withshotonnetwhistle'}

embedding_text_series = df_events['embedding_text_clean'].fillna('').astype(str).str.strip()
compact_series = embedding_text_series.str.lower().str.replace(r'[^a-z0-9]', '', regex=True)
leak_mask = embedding_text_series.str.contains(leak_regex, na=False) | compact_series.isin(blocked_compact_tokens)

n_leaks = int(leak_mask.sum())
print(f"Leakage check before embedding: {n_leaks:,} rows flagged")
if n_leaks > 0:
    print("Sample leaked rows (up to 10):")
    print(df_events.loc[leak_mask, ['game_id', 'sequence_id', 'sl_event_id', 'embedding_text_clean']].head(10).to_string(index=False))
    raise ValueError("Leakage tokens detected in embedding_text_clean. Clean these rows before embedding.")

# Select device for text embedding
if torch.xpu.is_available():
    device = torch.device("xpu")
    print("✓ Using Intel XPU (Arc GPU) for text embeddings")
elif torch.cuda.is_available():
    device = torch.device("cuda")
    print("✓ Using CUDA GPU for text embeddings")
else:
    device = torch.device("cpu")
    print("⚠ Using CPU for text embeddings (will be slower)")

# Load sentence transformer model
print(f"\nLoading SentenceTransformer model: all-MiniLM-L6-v2...")
model = SentenceTransformer('all-MiniLM-L6-v2', device=str(device))
print(f"✓ Model loaded (embedding dimension: {model.get_sentence_embedding_dimension()})")

# Use embedding_text_clean directly for text embeddings
df_events['embedding_text_clean'] = embedding_text_series
unique_texts = pd.unique(df_events['embedding_text_clean'])

print(f"\n✓ Prepared embedding_text_clean for encoding")
print(f"  Total events: {len(df_events):,}")
print(f"  Unique text combinations: {len(unique_texts):,}")

# Encode unique texts (with normalized embeddings)
print(f"\nEncoding unique texts (this may take a few minutes)...")
print(f"  Device: {device}")
print(f"  Batch size: 32")

unique_embeddings = model.encode(
    unique_texts.tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
    convert_to_numpy=True
)

print(f"\n✓ Encoded {len(unique_texts):,} unique texts")
print(f"  Embedding shape: {unique_embeddings.shape}")

# Create mapping from text to embedding index
text_to_idx = {text: idx for idx, text in enumerate(unique_texts)}

# Map all events to embedding indices (for final dataset join-back)
df_events['text_embedding_idx'] = df_events['embedding_text_clean'].map(text_to_idx).astype('int32')

print(f"\n✓ Mapped all events to embedding indices")
print(f"  Index range: [0, {df_events['text_embedding_idx'].max()}]")

# Save embeddings as separate .npy file
embeddings_output_path = OUTPUT_DIR / "text_embeddings.npy"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
np.save(embeddings_output_path, unique_embeddings.astype(np.float32))

print(f"\n✓ Saved text embeddings to: {embeddings_output_path}")
print(f"  Shape: {unique_embeddings.shape}")
print(f"  Size: {embeddings_output_path.stat().st_size / 1024 / 1024:.2f} MB")
print(f"  Format: float32, L2-normalized")

# Save explicit embedding index map for traceability
embedding_map_path = OUTPUT_DIR / "text_embedding_idx_map.parquet"
pd.DataFrame({
    'text_embedding_idx': np.arange(len(unique_texts), dtype=np.int32),
    'embedding_text_clean': unique_texts
}).to_parquet(embedding_map_path, index=False)
print(f"✓ Saved embedding index map to: {embedding_map_path}")

# Save updated events dataframe with embedding index
events_output_path = OUTPUT_DIR / "events_with_embedding_indices.parquet"
df_events.to_parquet(events_output_path, index=False)
print(f"\n✓ Saved updated events dataframe with embedding indices to: {events_output_path}")
print(f"  Shape: {df_events.shape}")
print(f"  Size: {events_output_path.stat().st_size / 1024 / 1024:.2f} MB")

# Verify sample embedding
sample_idx = 0
sample_text = unique_texts[sample_idx]
sample_embedding = unique_embeddings[sample_idx]
print(f"\nSample embedding:")
print(f"  Text: '{sample_text[:100]}...'")
print(f"  Embedding norm: {np.linalg.norm(sample_embedding):.6f} (should be ≈1.0)")
print(f"  First 5 dims: {sample_embedding[:5]}")

✓ sentence-transformers already installed
✓ Intel Extension for PyTorch available (version: 2.6.10+xpu)
Leakage check before embedding: 0 rows flagged
✓ Using Intel XPU (Arc GPU) for text embeddings

Loading SentenceTransformer model: all-MiniLM-L6-v2...


Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


✓ Model loaded (embedding dimension: 384)

✓ Prepared embedding_text_clean for encoding
  Total events: 1,658,796
  Unique text combinations: 2,539

Encoding unique texts (this may take a few minutes)...
  Device: xpu
  Batch size: 32


Batches:   0%|          | 0/80 [00:00<?, ?it/s]


✓ Encoded 2,539 unique texts
  Embedding shape: (2539, 384)

✓ Mapped all events to embedding indices
  Index range: [0, 2538]

✓ Saved text embeddings to: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\text_embeddings.npy
  Shape: (2539, 384)
  Size: 3.72 MB
  Format: float32, L2-normalized
✓ Saved embedding index map to: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\text_embedding_idx_map.parquet

✓ Saved updated events dataframe with embedding indices to: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\events_with_embedding_indices.parquet
  Shape: (1658796, 127)
  Size: 376.29 MB

Sample embedding:
  Text: 'neutral zone faceoff ; centerfodot, righthandedopponent...'
  Embedding norm: 1.000000 (should be ≈1.0)
  First 5 dims: [-0.02022606 -0.03467325 -0.06204727 -0.00104433  0.01249718]


In [4]:
# Load pre-computed df_events with text_embedding_idx and embeddings from saved files
df_events_path = OUTPUT_DIR / "events_with_embedding_indices.parquet"
embeddings_path = OUTPUT_DIR / "text_embeddings.npy"
embedding_map_path = OUTPUT_DIR / "text_embedding_idx_map.parquet"

if df_events_path.exists() and embeddings_path.exists():
    # Load from saved files
    df_events = pd.read_parquet(df_events_path)
    text_embeddings = np.load(embeddings_path)
    print(f"✓ Loaded df_events from: {df_events_path}")
    print(f"  Shape: {df_events.shape}")
    print(f"  Columns: {list(df_events.columns[:20])}{'...' if len(df_events.columns) > 20 else ''}")
    print(f"✓ Loaded text embeddings from: {embeddings_path}")
    print(f"  Shape: {text_embeddings.shape}")
    print(f"✓ text_embedding_idx column exists: {'text_embedding_idx' in df_events.columns}")

    if embedding_map_path.exists():
        df_embedding_map = pd.read_parquet(embedding_map_path)
        print(f"✓ Loaded embedding index map from: {embedding_map_path}")
        print(f"  Mapping rows: {len(df_embedding_map):,}")
    else:
        print(f"⚠ text_embedding_idx map not found at: {embedding_map_path}")
else:
    missing = []
    if not df_events_path.exists():
        missing.append(f"df_events: {df_events_path}")
    if not embeddings_path.exists():
        missing.append(f"embeddings: {embeddings_path}")
    print(f"⚠ Warning: Missing saved files:\n  {', '.join(missing)}")
    print(f"  Please run the embedding generation cell first.")

# Build vocabularies for categorical features (reserve 0 for padding, 1 for unknown)
vocabs = {}

for feature in CATEGORICAL_FEATURES:
    unique_values = df_events[feature].dropna().unique()
    # Create vocab: {value: id}, starting from 2 (0=PAD, 1=UNK)
    vocab = {'<PAD>': 0, '<UNK>': 1}
    for idx, val in enumerate(sorted(unique_values)):
        vocab[val] = idx + 2
    
    vocabs[feature] = vocab
    
    print(f"{feature} vocabulary:")
    print(f"  Unique values: {len(unique_values)}")
    print(f"  Vocab size (with PAD/UNK): {len(vocab)}")
    if len(unique_values) <= 30:
        print(f"  Values: {sorted(unique_values)}")
    print()

# Apply encoding
for feature in CATEGORICAL_FEATURES:
    df_events[f'{feature}_id'] = df_events[feature].map(vocabs[feature]).fillna(1).astype(int)  # UNK=1

print(f"{'='*80}")
print(f"✓ Encoded {len(CATEGORICAL_FEATURES)} categorical features")
print(f"{'='*80}")

print(f"\nSample encodings:")
sample_cols = []
for feat in CATEGORICAL_FEATURES:
    sample_cols.extend([feat, f'{feat}_id'])

print(df_events[sample_cols].head(10))

✓ Loaded df_events from: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\events_with_embedding_indices.parquet
  Shape: (1658796, 127)
  Columns: ['game_id', 'period', 'period_time', 'game_stint', 'sequence_id', 'player_id', 'team_id', 'opp_team_id', 'event_type', 'outcome', 'flags', 'flags_clean', 'description', 'description_clean', 'detail', 'x', 'y', 'x_adj', 'y_adj', 'has_tracking_data']...
✓ Loaded text embeddings from: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\text_embeddings.npy
  Shape: (2539, 384)
✓ text_embedding_idx column exists: True
✓ Loaded embedding index map from: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\text_embedding_idx_map.parquet
  Mapping rows: 2,539
event_type vocabulary:
  Unique values: 24
  Vocab size (with PAD/UNK): 26
  Values: ['block', 'carry', 'check', 'controlledbreakout', 'controlledentryagainst', 'deflection', 'dum

### Add EOS (End-of-Sequence) Tokens

Add explicit EOS tokens for sequence terminators (whistle, goal, period end, etc.) to help model learn sequence boundaries.

In [5]:
# Define sequence terminator event types that should get EOS token
TERMINATOR_EVENTS = [
    'whistle',
    'goal',
    'end_of_period',  # Note: matches actual event_type name in data
]

# Add is_eos flag for last event in each sequence
df_events['is_last_in_seq'] = False
last_event_idx = df_events.groupby(['game_id', 'sequence_id']).tail(1).index
df_events.loc[last_event_idx, 'is_last_in_seq'] = True

# Mark as EOS if it's last event AND is a terminator type
df_events['is_eos'] = (
    df_events['is_last_in_seq'] & 
    df_events['event_type'].isin(TERMINATOR_EVENTS)
).astype(int)

print(f"EOS Token Statistics:")
print(f"{'='*80}")
print(f"  Total events: {len(df_events):,}")
print(f"  Last events in sequences: {df_events['is_last_in_seq'].sum():,}")
print(f"  EOS tokens (terminator as last): {df_events['is_eos'].sum():,}")
print(f"  EOS percentage: {df_events['is_eos'].mean()*100:.2f}%")

print(f"\nEOS tokens by event type:")
eos_by_type = df_events[df_events['is_eos'] == 1]['event_type'].value_counts()
for event_type, count in eos_by_type.items():
    pct = count / df_events['is_eos'].sum() * 100
    print(f"  {event_type:20s}: {count:>8,} ({pct:>5.1f}%)")

print(f"\n✓ Added is_eos flag (will be used as binary feature in model)")

EOS Token Statistics:
  Total events: 1,658,796
  Last events in sequences: 28,095
  EOS tokens (terminator as last): 28,095
  EOS percentage: 1.69%

EOS tokens by event type:
  whistle             :   25,273 ( 90.0%)
  goal                :    2,810 ( 10.0%)
  end_of_period       :       12 (  0.0%)

✓ Added is_eos flag (will be used as binary feature in model)


In [6]:
# Analyze sequences
print("Sequence Analysis:")
print("=" * 80)

# Group by game and sequence
sequence_info = df_events.groupby(['game_id', 'sequence_id']).agg({
    'event_type': ['count', 'first', 'last'],
    'team_id': 'first',
    'period': 'first'
}).reset_index()

sequence_info.columns = ['game_id', 'sequence_id', 'event_count', 'first_event', 'last_event', 'team_id', 'period']

print(f"Total sequences: {len(sequence_info):,}")
print(f"\nSequence length statistics:")
print(sequence_info['event_count'].describe())

print(f"\nLast event types (sequence terminators):")
print(sequence_info['last_event'].value_counts())

print(f"\nFirst event types:")
print(sequence_info['first_event'].value_counts().head(10))

Sequence Analysis:
Total sequences: 28,095

Sequence length statistics:
count    28095.000000
mean        59.042392
std         50.527544
min          4.000000
25%         23.000000
50%         45.000000
75%         80.000000
max        508.000000
Name: event_count, dtype: float64

Last event types (sequence terminators):
last_event
whistle          25273
goal              2810
end_of_period       12
Name: count, dtype: int64

First event types:
first_event
faceoff         28084
lpr                 9
penaltydrawn        1
penalty             1
Name: count, dtype: int64


In [7]:
# Legacy sequence-outcome extraction is deprecated for continuous-state modeling.
# Keep this cell as an audit-only check to avoid accidental reuse.

print("Legacy sequence-outcome target path is retired.")
print("Using dynamic-horizon actor-relative target logic in the next cell as the single source of truth.")

# Optional audit: count goal events and their sequence-terminal status
n_goals = int((df_events['event_type'] == 'goal').sum())
print(f"\nGoal events in dataset: {n_goals:,}")

if 'is_last_in_seq' in df_events.columns:
    goals_last = int(((df_events['event_type'] == 'goal') & (df_events['is_last_in_seq'] == True)).sum())
    print(f"Goals that are last in sequence: {goals_last:,}")

# Explicitly avoid creating any sequence-level outcome lookup used by downstream target assignment
df_outcomes = None

Legacy sequence-outcome target path is retired.
Using dynamic-horizon actor-relative target logic in the next cell as the single source of truth.

Goal events in dataset: 2,810
Goals that are last in sequence: 2,810


In [8]:
# Diagnostic: inspect penalty detail/description coverage before dynamic horizon logic
print("=" * 80)
print("PENALTY DETAIL DIAGNOSTIC (detail + description_clean)")
print("=" * 80)

detail_series = df_events.get('detail', pd.Series('', index=df_events.index)).astype(str)
desc_series = df_events.get('description_clean', pd.Series('', index=df_events.index)).astype(str)

penalty_rows = df_events.loc[df_events['event_type'].eq('penalty')].copy()
print(f"Total penalty rows: {len(penalty_rows):,}")

if len(penalty_rows) > 0:
    detail_nonempty = penalty_rows['detail'].notna() & penalty_rows['detail'].astype(str).str.strip().ne('') if 'detail' in penalty_rows.columns else pd.Series(False, index=penalty_rows.index)
    desc_nonempty = penalty_rows['description_clean'].notna() & penalty_rows['description_clean'].astype(str).str.strip().ne('') if 'description_clean' in penalty_rows.columns else pd.Series(False, index=penalty_rows.index)

    print(f"Rows with non-empty detail: {int(detail_nonempty.sum()):,} ({detail_nonempty.mean()*100:.1f}%)")
    print(f"Rows with non-empty description_clean: {int(desc_nonempty.sum()):,} ({desc_nonempty.mean()*100:.1f}%)")

    if 'detail' in penalty_rows.columns:
        print("\nTop detail values (penalty rows):")
        print(penalty_rows['detail'].fillna('<NA>').value_counts().head(20))

    show_cols = [
        'game_id', 'period', 'period_time', 'sequence_id', 'event_type',
        'team_id', 'player_id', 'detail', 'description_clean'
    ]
    show_cols = [c for c in show_cols if c in penalty_rows.columns]

    print("\nSample penalty rows (up to 25):")
    print(penalty_rows[show_cols].head(25).to_string(index=False))
else:
    print("No penalty rows found in df_events.")

print("=" * 80)

PENALTY DETAIL DIAGNOSTIC (detail + description_clean)
Total penalty rows: 3,917
Rows with non-empty detail: 3,917 (100.0%)
Rows with non-empty description_clean: 3,917 (100.0%)

Top detail values (penalty rows):
detail
tripping                  720
roughing                  527
hooking                   503
slashing                  381
interference              353
holding                   323
highsticking              317
crosschecking             279
boarding                   95
puckoverglass              93
toomanymen                 69
unsportsmanlikeconduct     57
holdingthestick            40
goalieinterference         30
elbowing                   26
instigator                 19
otherinfraction            15
embelishment               14
delayofgame                14
kneeing                    10
Name: count, dtype: int64

Sample penalty rows (up to 25):
                             game_id  period  period_time  sequence_id event_type                              team_id   

In [9]:
# Strict event-level dedupe before dynamic target engineering
print("=" * 80)
print("PRE-TARGET STRICT DEDUPE")
print("=" * 80)

dedupe_keys_preferred = [
    'game_id', 'period', 'sequence_id', 'sl_event_id',
    'event_type', 'team_id', 'player_id', 'period_time'
 ]
dedupe_keys = [c for c in dedupe_keys_preferred if c in df_events.columns]

if len(dedupe_keys) < 4:
    raise ValueError(
        "Not enough dedupe keys available for safe strict dedupe. "
        f"Available keys: {dedupe_keys}"
    )

rows_before = len(df_events)
dup_mask = df_events.duplicated(subset=dedupe_keys, keep='first')
dup_rows = int(dup_mask.sum())

if dup_rows > 0:
    dup_groups = int(df_events.groupby(dedupe_keys, dropna=False).size().gt(1).sum())
    print(f"Rows before dedupe: {rows_before:,}")
    print(f"Duplicate rows to drop: {dup_rows:,}")
    print(f"Duplicate key-groups: {dup_groups:,}")

    df_events = df_events.loc[~dup_mask].copy().reset_index(drop=True)
    print(f"Rows after dedupe: {len(df_events):,}")
else:
    print(f"Rows before dedupe: {rows_before:,}")
    print("No duplicate rows found for strict event key")

print(f"Dedupe keys used: {dedupe_keys}")
print("=" * 80)

PRE-TARGET STRICT DEDUPE
Rows before dedupe: 1,658,796
Duplicate rows to drop: 384
Duplicate key-groups: 128
Rows after dedupe: 1,658,412
Dedupe keys used: ['game_id', 'period', 'sequence_id', 'sl_event_id', 'event_type', 'team_id', 'player_id', 'period_time']


In [10]:
# Dynamic-horizon target engineering (continuous-state framing)
# ------------------------------------------------------------------
# Target classes (actor-relative):
#   0 = possession team scores within horizon
#   1 = opposing team scores within horizon
#   2 = no goal within horizon

print("=" * 80)
print("DYNAMIC HORIZON TARGET ENGINEERING (ACTOR-RELATIVE, 3-CLASS)")
print("=" * 80)

CLASS_POSS_GOAL = 0
CLASS_DEF_GOAL = 1
CLASS_NO_GOAL = 2

# Hard schema gate at target step as well (defensive against partial reruns)
required_target_cols = [
    'game_id', 'period', 'period_time', 'event_type', 'team_id',
    'player_id', 'detail', 'sequence_id', 'sl_event_id',
    'game_time_sec', 'is_boundary_event', 'is_end_of_period'
 ]
missing_target_cols = [col for col in required_target_cols if col not in df_events.columns]
if missing_target_cols:
    raise KeyError(
        "Phase 3 hard-fail: missing required columns for dynamic target engineering: "
        f"{missing_target_cols}. Re-run updated Phase 2/earlier Phase 3 cells."
    )

# Preserve current ordering unless abnormal temporal drift is detected
# Abnormal = period_time delta < -1 within (game_id, period, sequence_id)
df_events['period_time'] = pd.to_numeric(df_events['period_time'], errors='coerce')
seq_keys = ['game_id', 'period', 'sequence_id']
delta = df_events.groupby(seq_keys, sort=False)['period_time'].diff()
abnormal_mask = delta < -1
n_abnormal = int(abnormal_mask.sum())
n_abnormal_seq = int(df_events.loc[abnormal_mask, seq_keys].drop_duplicates().shape[0])
print(f"Abnormal period_time deltas (< -1): {n_abnormal:,} across {n_abnormal_seq:,} sequences")

if n_abnormal > 0:
    time_sort_cols = ['game_id', 'period', 'game_time_sec', 'period_time']
    if 'sl_event_id' in df_events.columns:
        time_sort_cols.append('sl_event_id')
    if 'sequence_event_id' in df_events.columns:
        time_sort_cols.append('sequence_event_id')
    df_events = df_events.sort_values(time_sort_cols, kind='mergesort').reset_index(drop=True)
    print("Applied corrective temporal resort for dynamic horizon due to abnormality.")
else:
    df_events = df_events.reset_index(drop=True)
    print("No abnormality detected; preserving current event ordering for dynamic horizon.")
df_events['_row_id'] = np.arange(len(df_events), dtype=np.int64)

# Base rows eligible for temporal lookups (period_time required)
base_times = df_events[['_row_id', 'game_id', 'period', 'period_time']].copy()
base_times = base_times.dropna(subset=['period_time'])

def assign_next_time_by_group(base_df, ref_df, value_col):
    """Assign strictly next event time per (game_id, period) using searchsorted."""
    out = np.full(len(df_events), np.nan, dtype=float)
    if base_df.empty or ref_df.empty:
        return out

    ref_groups = {
        key: grp[value_col].to_numpy(dtype=float)
        for key, grp in ref_df.groupby(['game_id', 'period'], sort=False)
    }

    for key, grp in base_df.groupby(['game_id', 'period'], sort=False):
        ref_times = ref_groups.get(key)
        if ref_times is None or len(ref_times) == 0:
            continue

        t = grp['period_time'].to_numpy(dtype=float)
        idx = np.searchsorted(ref_times, t, side='right')  # strictly future
        valid = idx < len(ref_times)
        if not np.any(valid):
            continue

        row_ids = grp['_row_id'].to_numpy(dtype=np.int64)[valid]
        out[row_ids] = ref_times[idx[valid]]

    return out

def assign_next_goal_by_group(base_df, goals_df):
    """Assign strictly next goal time and team per (game_id, period) using searchsorted."""
    out_time = np.full(len(df_events), np.nan, dtype=float)
    out_team = np.empty(len(df_events), dtype=object)
    out_team[:] = np.nan
    if base_df.empty or goals_df.empty:
        return out_time, out_team

    grouped_goals = {
        key: (
            grp['next_goal_time'].to_numpy(dtype=float),
            grp['next_goal_team_id'].to_numpy(dtype=object)
        )
        for key, grp in goals_df.groupby(['game_id', 'period'], sort=False)
    }

    for key, grp in base_df.groupby(['game_id', 'period'], sort=False):
        goal_pack = grouped_goals.get(key)
        if goal_pack is None:
            continue

        goal_times, goal_teams = goal_pack
        if len(goal_times) == 0:
            continue

        t = grp['period_time'].to_numpy(dtype=float)
        idx = np.searchsorted(goal_times, t, side='right')  # strictly future
        valid = idx < len(goal_times)
        if not np.any(valid):
            continue

        row_ids = grp['_row_id'].to_numpy(dtype=np.int64)[valid]
        out_time[row_ids] = goal_times[idx[valid]]
        out_team[row_ids] = goal_teams[idx[valid]]

    return out_time, out_team

# ------------------------------------------------------------------
# 1) Build dynamic horizon_end_time
#    Rule A: default +20s
#    Rule B: penalty + penaltydrawn use next faceoff + 120s (no severity split)
#    Rule C: cap by period max time
# ------------------------------------------------------------------
PERIOD_MAX_FALLBACK = 1200.0
DEFAULT_HORIZON_SEC = 20.0
PENALTY_WINDOW_SEC = 120.0

# Per-(game, period) cap (no cross-period bleeding)
period_cap = df_events.groupby(['game_id', 'period'])['period_time'].transform('max')
period_cap = period_cap.clip(upper=PERIOD_MAX_FALLBACK)
df_events['period_cap_time'] = period_cap

# Default horizon
df_events['horizon_end_time'] = df_events['period_time'] + DEFAULT_HORIZON_SEC

# Next faceoff time (strictly future within same game/period)
faceoffs = df_events[df_events['event_type'] == 'faceoff'][['game_id', 'period', 'period_time']].copy()
faceoffs = faceoffs.dropna(subset=['period_time'])
faceoffs = faceoffs.rename(columns={'period_time': 'next_faceoff_time'})
faceoffs = faceoffs.sort_values(['game_id', 'period', 'next_faceoff_time'], kind='mergesort')

df_events['next_faceoff_time'] = assign_next_time_by_group(base_times, faceoffs, 'next_faceoff_time')

# penalty + penaltydrawn receive the same 120-second extension from next faceoff
is_penalty_window_event = df_events['event_type'].isin(['penalty', 'penaltydrawn'])
df_events['penalty_window_sec'] = np.where(is_penalty_window_event, PENALTY_WINDOW_SEC, np.nan)

has_faceoff_for_penalty = is_penalty_window_event & df_events['next_faceoff_time'].notna()
df_events.loc[has_faceoff_for_penalty, 'horizon_end_time'] = (
    df_events.loc[has_faceoff_for_penalty, 'next_faceoff_time']
    + df_events.loc[has_faceoff_for_penalty, 'penalty_window_sec']
)

# Cap horizon at period boundary
df_events['horizon_end_time'] = np.minimum(df_events['horizon_end_time'], df_events['period_cap_time'])

# ------------------------------------------------------------------
# 2) sec_next_stoppage (next whistle/goal/end_of_period)
# ------------------------------------------------------------------
stoppages = df_events[
    df_events['event_type'].isin(['whistle', 'goal', 'end_of_period'])
][['game_id', 'period', 'period_time']].copy()
stoppages = stoppages.dropna(subset=['period_time'])
stoppages = stoppages.rename(columns={'period_time': 'next_stoppage_time'})
stoppages = stoppages.sort_values(['game_id', 'period', 'next_stoppage_time'], kind='mergesort')

df_events['next_stoppage_time'] = assign_next_time_by_group(base_times, stoppages, 'next_stoppage_time')
df_events['sec_next_stoppage'] = df_events['next_stoppage_time'] - df_events['period_time']

# ------------------------------------------------------------------
# 3) Dynamic-window goal evaluation using earliest future goal priority
# ------------------------------------------------------------------
goals = df_events[df_events['event_type'] == 'goal'][['game_id', 'period', 'period_time', 'team_id']].copy()
goals = goals.dropna(subset=['period_time'])
goals = goals.rename(columns={'period_time': 'next_goal_time', 'team_id': 'next_goal_team_id'})
goals = goals.sort_values(['game_id', 'period', 'next_goal_time'], kind='mergesort')

next_goal_time, next_goal_team = assign_next_goal_by_group(base_times, goals)
df_events['next_goal_time'] = next_goal_time
df_events['next_goal_team_id'] = next_goal_team

in_dynamic_horizon = (
    df_events['next_goal_time'].notna()
    & (df_events['next_goal_time'] <= df_events['horizon_end_time'])
)

# Actor-relative 3-class target
if 'target' in df_events.columns:
    df_events = df_events.drop(columns=['target'])

df_events['target'] = CLASS_NO_GOAL

valid_actor_team = df_events['team_id'].notna()
poss_goal_mask = in_dynamic_horizon & valid_actor_team & (df_events['next_goal_team_id'] == df_events['team_id'])
def_goal_mask = in_dynamic_horizon & valid_actor_team & (df_events['next_goal_team_id'] != df_events['team_id'])

df_events.loc[poss_goal_mask, 'target'] = CLASS_POSS_GOAL
df_events.loc[def_goal_mask, 'target'] = CLASS_DEF_GOAL

# ------------------------------------------------------------------
# 4) Diagnostics / invariants
# ------------------------------------------------------------------
print("\nHorizon diagnostics:")
print(f"  Rows with horizon_end_time: {df_events['horizon_end_time'].notna().sum():,} / {len(df_events):,}")
print(f"  Penalty-window events (penalty + penaltydrawn): {is_penalty_window_event.sum():,}")
print(f"  Penalty-window rows with +120s override: {has_faceoff_for_penalty.sum():,}")
print(f"  Penalty-window rows missing next faceoff (kept default +20s): {(is_penalty_window_event & df_events['next_faceoff_time'].isna()).sum():,}")
print(f"  Rows with sec_next_stoppage: {df_events['sec_next_stoppage'].notna().sum():,}")

# Ensure no cross-period horizon overflow
overflow = int((df_events['horizon_end_time'] > df_events['period_cap_time']).sum())
print(f"  Horizon overflow rows (should be 0): {overflow}")

# Ensure earliest-goal priority creates mutually exclusive class assignment
both_goal_classes = int((poss_goal_mask & def_goal_mask).sum())
print(f"  Rows marked both poss+def (should be 0): {both_goal_classes}")

# Additional invariants
negative_stoppage = int((df_events['sec_next_stoppage'] < 0).fillna(False).sum())
print(f"  Negative sec_next_stoppage rows (should be 0): {negative_stoppage}")

invalid_targets = int((~df_events['target'].isin([CLASS_POSS_GOAL, CLASS_DEF_GOAL, CLASS_NO_GOAL])).sum())
print(f"  Invalid target labels (should be 0): {invalid_targets}")

print(f"\n{'='*80}")
print("TARGET DISTRIBUTION (DYNAMIC HORIZON, ACTOR-RELATIVE)")
print(f"{'='*80}")

target_counts = df_events['target'].value_counts().sort_index()
target_pcts = df_events['target'].value_counts(normalize=True).sort_index() * 100

target_names = {
    CLASS_POSS_GOAL: 'Possession Goal',
    CLASS_DEF_GOAL: 'Defending Goal',
    CLASS_NO_GOAL: 'No Goal',
 }

for target_class in sorted(target_names.keys()):
    class_name = target_names[target_class]
    count = int(target_counts.get(target_class, 0))
    pct = float(target_pcts.get(target_class, 0.0))
    print(f"  Class {target_class} ({class_name:15s}): {count:>9,} ({pct:>5.2f}%)")

print(f"\n✓ Added dynamic horizon columns: horizon_end_time, sec_next_stoppage")
print("✓ Applied earliest-goal priority within dynamic window (no dual-class conflicts)")
print("=" * 80)

# cleanup helper
if '_row_id' in df_events.columns:
    df_events.drop(columns=['_row_id'], inplace=True)

DYNAMIC HORIZON TARGET ENGINEERING (ACTOR-RELATIVE, 3-CLASS)
Abnormal period_time deltas (< -1): 0 across 0 sequences
No abnormality detected; preserving current event ordering for dynamic horizon.

Horizon diagnostics:
  Rows with horizon_end_time: 1,658,412 / 1,658,412
  Penalty-window events (penalty + penaltydrawn): 7,581
  Penalty-window rows with +120s override: 7,470
  Penalty-window rows missing next faceoff (kept default +20s): 111
  Rows with sec_next_stoppage: 1,656,794
  Horizon overflow rows (should be 0): 0
  Rows marked both poss+def (should be 0): 0
  Negative sec_next_stoppage rows (should be 0): 0
  Invalid target labels (should be 0): 0

TARGET DISTRIBUTION (DYNAMIC HORIZON, ACTOR-RELATIVE)
  Class 0 (Possession Goal):    41,418 ( 2.50%)
  Class 1 (Defending Goal ):    22,201 ( 1.34%)
  Class 2 (No Goal        ): 1,594,793 (96.16%)

✓ Added dynamic horizon columns: horizon_end_time, sec_next_stoppage
✓ Applied earliest-goal priority within dynamic window (no dual-cla

In [11]:
# Post-horizon diagnostics: missing sec_next_stoppage / missing next_faceoff / penalty class mix
print("=" * 80)
print("POST-HORIZON EDGE CASE DIAGNOSTICS")
print("=" * 80)

required_diag_cols = ['event_type', 'target']
missing_diag = [c for c in required_diag_cols if c not in df_events.columns]
if missing_diag:
    raise KeyError(f"Missing required columns for diagnostics: {missing_diag}")

# ---------- 1) Sample rows with no sec_next_stoppage ----------
if 'sec_next_stoppage' in df_events.columns:
    no_stoppage = df_events['sec_next_stoppage'].isna()
    n_no_stoppage = int(no_stoppage.sum())
    print(f"\nRows with no sec_next_stoppage: {n_no_stoppage:,} / {len(df_events):,}")

    if n_no_stoppage > 0:
        dup_key_cols = [
            c for c in [
                'game_id', 'period', 'sequence_id', 'sl_event_id',
                'event_type', 'team_id', 'player_id', 'period_time'
            ] if c in df_events.columns
        ]
        if dup_key_cols:
            no_stop_subset = df_events.loc[no_stoppage, dup_key_cols].copy()
            duplicate_rows = int(no_stop_subset.duplicated(subset=dup_key_cols, keep=False).sum())
            duplicate_groups = int(no_stop_subset.groupby(dup_key_cols, dropna=False).size().gt(1).sum())
            print(f"  Duplicate-key rows within no-stoppage subset: {duplicate_rows:,}")
            print(f"  Duplicate-key groups within no-stoppage subset: {duplicate_groups:,}")

        show_cols_no_stop = [
            'game_id', 'period', 'period_time', 'game_time_sec', 'sequence_id',
            'sl_event_id', 'event_type', 'team_id', 'player_id', 'horizon_end_time',
            'next_stoppage_time', 'sec_next_stoppage', 'period_cap_time', 'target'
        ]
        show_cols_no_stop = [c for c in show_cols_no_stop if c in df_events.columns]
        print("Sample rows with missing sec_next_stoppage (up to 25):")
        print(
            df_events.loc[no_stoppage, show_cols_no_stop]
            .sort_values([c for c in ['game_id', 'period', 'period_time', 'sl_event_id'] if c in show_cols_no_stop], kind='mergesort')
            .head(25)
            .to_string(index=False)
        )
    else:
        print("✓ No rows with missing sec_next_stoppage")
else:
    print("\nColumn 'sec_next_stoppage' not present. Run dynamic horizon cell first.")

# ---------- 2) Penalty-window rows missing next faceoff ----------
if 'next_faceoff_time' in df_events.columns:
    penalty_window_mask = df_events['event_type'].isin(['penalty', 'penaltydrawn'])
    missing_faceoff_for_penalty = penalty_window_mask & df_events['next_faceoff_time'].isna()
    n_penalty_missing_faceoff = int(missing_faceoff_for_penalty.sum())
    print(f"\nPenalty-window rows missing next_faceoff_time: {n_penalty_missing_faceoff:,} / {int(penalty_window_mask.sum()):,}")

    missing_by_type = df_events.loc[missing_faceoff_for_penalty, 'event_type'].value_counts()
    if len(missing_by_type) > 0:
        print("  Missing next_faceoff by event_type:")
        for et, cnt in missing_by_type.items():
            print(f"    {et}: {int(cnt):,}")

    if n_penalty_missing_faceoff > 0:
        show_cols_pen = [
            'game_id', 'period', 'period_time', 'game_time_sec', 'sequence_id',
            'sl_event_id', 'event_type', 'detail', 'description_clean', 'team_id', 'player_id',
            'next_faceoff_time', 'penalty_window_sec', 'horizon_end_time', 'period_cap_time',
            'next_stoppage_time', 'sec_next_stoppage', 'target'
        ]
        show_cols_pen = [c for c in show_cols_pen if c in df_events.columns]
        print("Sample penalty-window rows missing next_faceoff_time (up to 25):")
        print(
            df_events.loc[missing_faceoff_for_penalty, show_cols_pen]
            .sort_values([c for c in ['game_id', 'period', 'period_time', 'sl_event_id'] if c in show_cols_pen], kind='mergesort')
            .head(25)
            .to_string(index=False)
        )
    else:
        print("✓ Every penalty-window row has a next_faceoff_time")
else:
    print("\nColumn 'next_faceoff_time' not present. Run dynamic horizon cell first.")

# ---------- 3) Class distribution for penalty + penaltydrawn ----------
focus_events = ['penalty', 'penaltydrawn']
focus_mask = df_events['event_type'].isin(focus_events)
focus_df = df_events.loc[focus_mask, ['event_type', 'target']].copy()

print("\n" + "-" * 80)
print("Target class distribution for penalty / penaltydrawn")
print("-" * 80)
print(f"Rows in scope: {len(focus_df):,}")

if len(focus_df) == 0:
    print("No penalty or penaltydrawn rows found.")
else:
    # Counts by event type and target
    dist_counts = (
        focus_df.groupby(['event_type', 'target'])
        .size()
        .unstack(fill_value=0)
        .sort_index()
    )

    # Ensure all 3 classes are visible in table
    for cls in [0, 1, 2]:
        if cls not in dist_counts.columns:
            dist_counts[cls] = 0
    dist_counts = dist_counts[[0, 1, 2]]

    print("Counts by event_type × target:")
    print(dist_counts.to_string())

    row_totals = dist_counts.sum(axis=1).replace(0, np.nan)
    dist_pct = (dist_counts.div(row_totals, axis=0) * 100).fillna(0.0)
    print("\nRow-wise % by event_type × target:")
    print(dist_pct.round(2).to_string())

    overall_counts = focus_df['target'].value_counts().reindex([0, 1, 2], fill_value=0)
    overall_pcts = (overall_counts / len(focus_df) * 100).round(2)
    print("\nOverall target distribution in penalty + penaltydrawn scope:")
    for cls in [0, 1, 2]:
        print(f"  Class {cls}: {int(overall_counts[cls]):,} ({overall_pcts[cls]:.2f}%)")

print("=" * 80)

POST-HORIZON EDGE CASE DIAGNOSTICS

Rows with no sec_next_stoppage: 1,618 / 1,658,412
  Duplicate-key rows within no-stoppage subset: 0
  Duplicate-key groups within no-stoppage subset: 0
Sample rows with missing sec_next_stoppage (up to 25):
                             game_id  period  period_time  game_time_sec  sequence_id  sl_event_id event_type                              team_id                            player_id  horizon_end_time  next_stoppage_time  sec_next_stoppage  period_cap_time  target
00b0366a-95c6-5250-2dae-e3dd5c4198bc       1      1200.00        1200.00           16         1170    whistle                                 None                                 None           1200.00                 NaN                NaN          1200.00       2
00b0366a-95c6-5250-2dae-e3dd5c4198bc       2      1200.00        2400.00           38         2357    whistle                                 None                                 None           1200.00                 NaN    

In [12]:
# Compact verification after penaltydrawn horizon update
print("=" * 80)
print("COMPACT PENALTY / DUPLICATE VERIFICATION")
print("=" * 80)

# Duplicate-key check in no-stoppage subset
no_stop_mask = df_events['sec_next_stoppage'].isna() if 'sec_next_stoppage' in df_events.columns else pd.Series(False, index=df_events.index)
dup_key_cols = [c for c in ['game_id', 'period', 'sequence_id', 'sl_event_id', 'event_type', 'team_id', 'player_id', 'period_time'] if c in df_events.columns]
if no_stop_mask.any() and dup_key_cols:
    no_stop_subset = df_events.loc[no_stop_mask, dup_key_cols].copy()
    dup_rows = int(no_stop_subset.duplicated(subset=dup_key_cols, keep=False).sum())
    dup_groups = int(no_stop_subset.groupby(dup_key_cols, dropna=False).size().gt(1).sum())
    print(f"No-stoppage rows: {int(no_stop_mask.sum()):,}")
    print(f"Duplicate-key rows in no-stoppage subset: {dup_rows:,}")
    print(f"Duplicate-key groups in no-stoppage subset: {dup_groups:,}")
else:
    print("No no-stoppage rows or duplicate-key columns unavailable")

# Penalty / penaltydrawn class distribution
scope = df_events[df_events['event_type'].isin(['penalty', 'penaltydrawn'])][['event_type', 'target']].copy()
if len(scope) == 0:
    print("No penalty/penaltydrawn rows found")
else:
    dist = scope.groupby(['event_type', 'target']).size().unstack(fill_value=0)
    for cls in [0, 1, 2]:
        if cls not in dist.columns:
            dist[cls] = 0
    dist = dist[[0, 1, 2]].sort_index()
    pct = (dist.div(dist.sum(axis=1), axis=0) * 100).round(2)
    print("\nCounts by event_type × target:")
    print(dist.to_string())
    print("\nRow-wise % by event_type × target:")
    print(pct.to_string())

# Opposite-label check among paired penalty/penaltydrawn moments
pair_keys = [c for c in ['game_id', 'period', 'sequence_id', 'period_time'] if c in df_events.columns]
pair_scope = df_events[df_events['event_type'].isin(['penalty', 'penaltydrawn'])][pair_keys + ['event_type', 'target']].copy()
if len(pair_keys) == 4 and len(pair_scope) > 0:
    penalties = pair_scope[pair_scope['event_type'] == 'penalty'][pair_keys + ['target']].rename(columns={'target': 'target_penalty'})
    draws = pair_scope[pair_scope['event_type'] == 'penaltydrawn'][pair_keys + ['target']].rename(columns={'target': 'target_drawn'})
    paired = penalties.merge(draws, on=pair_keys, how='inner')
    if len(paired) > 0:
        opposite_01 = (
            ((paired['target_penalty'] == 0) & (paired['target_drawn'] == 1))
            | ((paired['target_penalty'] == 1) & (paired['target_drawn'] == 0))
        )
        print(f"\nPaired penalty/penaltydrawn rows (same game/period/sequence/time): {len(paired):,}")
        print(f"Paired rows with opposite 0↔1 labels: {int(opposite_01.sum()):,} ({opposite_01.mean()*100:.2f}%)")
    else:
        print("\nNo direct penalty/penaltydrawn pairs found on game+period+sequence+period_time keys")
else:
    print("\nPair-key check skipped (required keys unavailable)")

print("=" * 80)

COMPACT PENALTY / DUPLICATE VERIFICATION
No-stoppage rows: 1,618
Duplicate-key rows in no-stoppage subset: 0
Duplicate-key groups in no-stoppage subset: 0

Counts by event_type × target:
target          0    1     2
event_type                  
penalty       158  692  2983
penaltydrawn  680  157  2911

Row-wise % by event_type × target:
target            0      1      2
event_type                       
penalty        4.12  18.05  77.82
penaltydrawn  18.14   4.19  77.67

Paired penalty/penaltydrawn rows (same game/period/sequence/time): 3,998
Paired rows with opposite 0↔1 labels: 837 (20.94%)


In [13]:
# Inspect shot outcomes to check for potential information leakage
print("=" * 80)
print("SHOT OUTCOME ANALYSIS (Checking for Target Leakage)")
print("=" * 80)

# Filter to shot events only
df_shots = df_events[df_events['event_type'] == 'shot'].copy()
print(f"\nTotal shot events: {len(df_shots):,}")

# Analyze shot outcomes
print(f"\nShot outcome distribution:")
shot_outcomes = df_shots['outcome'].value_counts()
shot_outcome_pcts = df_shots['outcome'].value_counts(normalize=True) * 100

for outcome, count in shot_outcomes.items():
    pct = shot_outcome_pcts[outcome]
    print(f"  {outcome:20s}: {count:>8,} ({pct:>5.2f}%)")

# Check: Are successful shots followed by goals?
print(f"\n{'='*80}")
print(f"CHECKING: Do 'successful' shots leak goal information?")
print(f"{'='*80}")

# For each shot, check if next event in sequence is a goal
df_shots['next_event_idx'] = df_shots.index + 1
df_shots['next_event_type'] = df_shots['next_event_idx'].map(
    df_events['event_type'].to_dict()
)
df_shots['followed_by_goal'] = df_shots['next_event_type'] == 'goal'

# Breakdown by outcome
print(f"\nShots followed by goal (immediate next event):")
for outcome in df_shots['outcome'].unique():
    outcome_shots = df_shots[df_shots['outcome'] == outcome]
    followed_by_goal = outcome_shots['followed_by_goal'].sum()
    total = len(outcome_shots)
    pct = (followed_by_goal / total * 100) if total > 0 else 0
    print(f"  {outcome:20s}: {followed_by_goal:>6,} / {total:>8,} ({pct:>5.2f}%)")

# Check: Correlation between shot success and sequence outcome
print(f"\n{'='*80}")
print(f"CHECKING: Shot outcomes vs sequence-level targets")
print(f"{'='*80}")

print(f"\nSuccessful shots by target class:")
successful_shots = df_shots[df_shots['outcome'] == 'successful']
for target_class, class_name in target_names.items():
    count = (successful_shots['target'] == target_class).sum()
    total = len(successful_shots)
    pct = (count / total * 100) if total > 0 else 0
    print(f"  Class {target_class} ({class_name:15s}): {count:>6,} / {total:>8,} ({pct:>5.2f}%)")

print(f"\nFailed shots by target class:")
failed_shots = df_shots[df_shots['outcome'] == 'failed']
for target_class, class_name in target_names.items():
    count = (failed_shots['target'] == target_class).sum()
    total = len(failed_shots)
    pct = (count / total * 100) if total > 0 else 0
    print(f"  Class {target_class} ({class_name:15s}): {count:>6,} / {total:>8,} ({pct:>5.2f}%)")

# Key insight: Check if successful shots are ALWAYS followed by goals
print(f"\n{'='*80}")
print(f"KEY LEAKAGE CHECK:")
print(f"{'='*80}")

successful_not_followed = successful_shots[~successful_shots['followed_by_goal']]
failed_followed = failed_shots[failed_shots['followed_by_goal']]

print(f"\nSuccessful shots NOT followed by goal: {len(successful_not_followed):,}")
print(f"Failed shots followed by goal: {len(failed_followed):,}")

if len(successful_not_followed) > 0:
    print(f"\n✓ 'successful' outcome does NOT perfectly predict goals")
    print(f"  {len(successful_not_followed)} successful shots did not result in goals")
    print(f"  Likely definition: 'successful' = on target (saved/blocked), not necessarily scored")
else:
    print(f"\n⚠️  WARNING: ALL successful shots are followed by goals!")
    print(f"   This would be severe target leakage - 'successful' = goal")

if len(failed_followed) > 0:
    print(f"\n⚠️  {len(failed_followed)} 'failed' shots were followed by goals")
    print(f"   This suggests complex scenarios (rebounds, deflections)")
else:
    print(f"\n✓ No 'failed' shots followed by goals (as expected)")

print(f"\n{'='*80}")
print(f"CONCLUSION:")
print(f"{'='*80}")
print(f"If 'successful' shots can occur without goals, there's no direct leakage.")
print(f"If ALL successful shots lead to goals, 'outcome' should be EXCLUDED from model.")
print("=" * 80)

SHOT OUTCOME ANALYSIS (Checking for Target Leakage)

Total shot events: 53,952

Shot outcome distribution:
  successful          :   30,592 (56.70%)
  failed              :   23,360 (43.30%)

CHECKING: Do 'successful' shots leak goal information?

Shots followed by goal (immediate next event):
  successful          :  2,367 /   30,592 ( 7.74%)
  failed              :      0 /   23,360 ( 0.00%)

CHECKING: Shot outcomes vs sequence-level targets

Successful shots by target class:
  Class 0 (Possession Goal):  3,736 /   30,592 (12.21%)
  Class 1 (Defending Goal ):    200 /   30,592 ( 0.65%)
  Class 2 (No Goal        ): 26,656 /   30,592 (87.13%)

Failed shots by target class:
  Class 0 (Possession Goal):    592 /   23,360 ( 2.53%)
  Class 1 (Defending Goal ):    195 /   23,360 ( 0.83%)
  Class 2 (No Goal        ): 22,573 /   23,360 (96.63%)

KEY LEAKAGE CHECK:

Successful shots NOT followed by goal: 28,225
Failed shots followed by goal: 0

✓ 'successful' outcome does NOT perfectly predict

### Goal Attribution Logic: Creating `target_xg` for xG Model

**Objective**: Create a binary label for the Transformer xG model that identifies shots/deflections that directly resulted in goals.

**Logic**:
1. Implement vectorized look-ahead to attribute goals to the **last shot or deflection** before the goal
2. **Filter out noise**: Ignore failed block events when determining scoring events
3. Rule: If `event_t+1` is a goal (or `event_t+2` if `t+1` is a failed block), and `event_t` is a shot/deflection, then `target_xg = 1`

**Why This Matters**:
- Traditional xG looks at a snapshot: Distance, Angle, Shot Type
- Our Transformer xG will capture **pre-shot context**: Fatigue, passing velocity, defensive pressure over the last 128 events
- This binary target allows direct comparison with `sl_xg_all_shots` as a baseline validation

In [14]:

print(f"\nsl_xg_all_shots statistics:")
print(df_events['sl_xg_all_shots'].describe())

# Check for missing values
print(f"\nMissing sl_xg_all_shots values: {df_events['sl_xg_all_shots'].isna().sum():,} ({df_events['sl_xg_all_shots'].isna().mean()*100:.2f}%)")
print(f"  Events with sl_xg_all_shots: {df_events['sl_xg_all_shots'].notna().sum():,} ({df_events['sl_xg_all_shots'].notna().mean()*100:.2f}%)")
print(f"  sl_xg_all_shots range: [{df_events['sl_xg_all_shots'].min():.4f}, {df_events['sl_xg_all_shots'].max():.4f}]")


sl_xg_all_shots statistics:
count    53971.000000
mean         0.051495
std          0.087526
min          0.000610
25%          0.004268
50%          0.017889
75%          0.059196
max          0.938368
Name: sl_xg_all_shots, dtype: float64

Missing sl_xg_all_shots values: 1,604,441 (96.75%)
  Events with sl_xg_all_shots: 53,971 (3.25%)
  sl_xg_all_shots range: [0.0006, 0.9384]


In [15]:
# Vectorized look-ahead logic to create target_xg
print("=" * 80)
print("CREATING BINARY TARGET_XG FOR TRANSFORMER XG MODEL")
print("=" * 80)

# ------------------------------------------------------------------
# 1) Preserve current event order unless abnormal temporal drift exists
#    Abnormal = period_time delta < -1 within (game_id, period, sequence_id)
# ------------------------------------------------------------------
required_cols = ['game_id', 'period', 'sequence_id', 'period_time', 'event_type', 'outcome']
missing_cols = [c for c in required_cols if c not in df_events.columns]
if missing_cols:
    raise KeyError(f"Missing required columns for xG target creation: {missing_cols}")

df_events['period_time'] = pd.to_numeric(df_events['period_time'], errors='coerce')
seq_keys = ['game_id', 'period', 'sequence_id']

delta = df_events.groupby(seq_keys, sort=False)['period_time'].diff()
abnormal_mask = delta < -1
n_abnormal = int(abnormal_mask.sum())
n_abnormal_seq = int(df_events.loc[abnormal_mask, seq_keys].drop_duplicates().shape[0])

print(f"Abnormal period_time deltas (< -1): {n_abnormal:,} across {n_abnormal_seq:,} sequences")

if n_abnormal > 0:
    print("Applying strict goal-adjacency reorder only because abnormality was detected...")

    import gc

    # Stable baseline ordering inside sequence for repair pass
    df_events.sort_values(['game_id', 'period', 'sequence_id', 'period_time'], kind='mergesort', inplace=True)
    df_events.reset_index(drop=True, inplace=True)
    df_events['_sort_key'] = df_events.index.astype(float)

    # Movers: event directly before goal that should be moved away from goal adjacency
    type_mover = {'lpr', 'penalty', 'penaltydrawn'}
    # Anchors: shot chain events that should remain adjacent to goal
    type_anchor = {'shot', 'deflection', 'block'}

    goal_indices = df_events.index[df_events['event_type'] == 'goal'].to_numpy()
    count_moved = 0

    for goal_idx in goal_indices:
        prev_idx = goal_idx - 1
        if prev_idx < 0:
            continue

        # Must stay inside sequence
        if df_events.at[prev_idx, 'sequence_id'] != df_events.at[goal_idx, 'sequence_id']:
            continue

        # Only act when goal-1 is a mover
        if df_events.at[prev_idx, 'event_type'] not in type_mover:
            continue

        mover_idx = prev_idx
        anchor_idx = None

        # Search up to 5 events backward from mover for shot-chain anchor
        start_search = max(0, mover_idx - 5)
        for curr_idx in range(mover_idx - 1, start_search - 1, -1):
            if df_events.at[curr_idx, 'sequence_id'] != df_events.at[goal_idx, 'sequence_id']:
                break

            etype = df_events.at[curr_idx, 'event_type']
            if etype in type_anchor:
                anchor_idx = curr_idx  # keep earliest valid in this short backward scan
            elif etype in type_mover:
                pass
            else:
                break

        if anchor_idx is not None:
            new_key = float(anchor_idx) - 0.5
            target_time = df_events.at[anchor_idx, 'period_time']

            df_events.at[mover_idx, '_sort_key'] = new_key
            df_events.at[mover_idx, 'period_time'] = target_time
            count_moved += 1

    if count_moved > 0:
        print(f"✓ Moved & synced {count_moved:,} mover events")
        df_events = df_events.sort_values(['game_id', 'period', 'sequence_id', '_sort_key'], kind='mergesort').reset_index(drop=True)
    else:
        print("✓ No mover events required goal-adjacency correction")

    df_events.drop(columns=['_sort_key'], inplace=True)
    gc.collect()
else:
    print("No abnormality detected; preserving current event ordering (no resort).")
    df_events = df_events.reset_index(drop=True)

# ------------------------------------------------------------------
# 2) Build target_xg from immediate look-ahead in preserved/corrected order
# ------------------------------------------------------------------
df_events['target_xg'] = 0

# Identify shots and deflections (potential scoring events)
shot_events = df_events['event_type'].isin(['shot', 'deflection'])

# Identify failed blocks
failed_block = (df_events['event_type'] == 'block') & (df_events['outcome'] == 'failed')

# Create shifted columns for look-ahead
df_events['next_event_type'] = df_events['event_type'].shift(-1)
df_events['next_outcome'] = df_events['outcome'].shift(-1)
df_events['next_next_event_type'] = df_events['event_type'].shift(-2)

# Track sequence boundaries (to avoid looking across sequences)
df_events['next_sequence_id'] = df_events['sequence_id'].shift(-1)
df_events['next_next_sequence_id'] = df_events['sequence_id'].shift(-2)
df_events['same_sequence_next'] = df_events['sequence_id'] == df_events['next_sequence_id']
df_events['same_sequence_next_next'] = df_events['sequence_id'] == df_events['next_next_sequence_id']

# Case 1: Shot/deflection followed directly by goal (no noise)
direct_scoring = (
    shot_events
    & (df_events['next_event_type'] == 'goal')
    & df_events['same_sequence_next']
 )

# Case 2: Shot/deflection followed by failed block, then goal
blocked_scoring = (
    shot_events
    & (df_events['next_event_type'] == 'block')
    & (df_events['next_outcome'] == 'failed')
    & (df_events['next_next_event_type'] == 'goal')
    & df_events['same_sequence_next_next']
 )

# Assign target_xg = 1 for scoring shots
df_events.loc[direct_scoring | blocked_scoring, 'target_xg'] = 1

# Clean up helper columns
df_events.drop(columns=[
    'next_event_type', 'next_outcome', 'next_next_event_type',
    'next_sequence_id', 'next_next_sequence_id',
    'same_sequence_next', 'same_sequence_next_next'
], inplace=True)

# Statistics
print(f"\nSHOT/DEFLECTION EVENT BREAKDOWN:")
print(f"  Total shots/deflections: {shot_events.sum():,}")
print(f"  Scoring shots (target_xg=1): {df_events['target_xg'].sum():,}")
print(f"  Non-scoring shots (target_xg=0): {(shot_events & (df_events['target_xg'] == 0)).sum():,}")
print(f"  Scoring rate: {df_events['target_xg'].sum() / max(1, shot_events.sum()) * 100:.2f}%")

print(f"\nDIRECT VS. BLOCKED SCORING SHOTS:")
print(f"  Direct scoring (shot → goal): {direct_scoring.sum():,}")
print(f"  Blocked scoring (shot → failed block → goal): {blocked_scoring.sum():,}")

print(f"\nTARGET_XG DISTRIBUTION:")
print(df_events['target_xg'].value_counts().sort_index())

print(f"\n✓ Created target_xg column for xG model training")
print("=" * 80)

CREATING BINARY TARGET_XG FOR TRANSFORMER XG MODEL
Abnormal period_time deltas (< -1): 0 across 0 sequences
No abnormality detected; preserving current event ordering (no resort).

SHOT/DEFLECTION EVENT BREAKDOWN:
  Total shots/deflections: 55,999
  Scoring shots (target_xg=1): 2,810
  Non-scoring shots (target_xg=0): 53,189
  Scoring rate: 5.02%

DIRECT VS. BLOCKED SCORING SHOTS:
  Direct scoring (shot → goal): 2,626
  Blocked scoring (shot → failed block → goal): 184

TARGET_XG DISTRIBUTION:
target_xg
0    1655602
1       2810
Name: count, dtype: int64

✓ Created target_xg column for xG model training


In [16]:
# Validate target_xg against sl_xg_all_shots
# Compare our binary target with Sportlogiq's continuous xG values

print("=" * 80)
print("COMPARING target_xg WITH sl_xg_all_shots")
print("=" * 80)

# Filter to shots/deflections only
shots_df = df_events[df_events['event_type'].isin(['shot', 'deflection'])].copy()

print(f"\nSHOT/DEFLECTION EVENTS:")
print(f"  Total: {len(shots_df):,}")
print(f"  With sl_xg_all_shots: {shots_df['sl_xg_all_shots'].notna().sum():,} ({shots_df['sl_xg_all_shots'].notna().mean()*100:.2f}%)")
print(f"  Scoring shots (target_xg=1): {(shots_df['target_xg'] == 1).sum():,}")

# Compare sl_xg_all_shots distributions for scoring vs non-scoring shots
scoring_shots = shots_df[shots_df['target_xg'] == 1]
non_scoring_shots = shots_df[shots_df['target_xg'] == 0]

print(f"\nsl_xg_all_shots COMPARISON:")
print(f"  Scoring shots (target_xg=1):")
print(f"    Mean sl_xg_all_shots: {scoring_shots['sl_xg_all_shots'].mean():.4f}")
print(f"    Median sl_xg_all_shots: {scoring_shots['sl_xg_all_shots'].median():.4f}")
print(f"    Max sl_xg_all_shots: {scoring_shots['sl_xg_all_shots'].max():.4f}")

print(f"  Non-scoring shots (target_xg=0):")
print(f"    Mean sl_xg_all_shots: {non_scoring_shots['sl_xg_all_shots'].mean():.4f}")
print(f"    Median sl_xg_all_shots: {non_scoring_shots['sl_xg_all_shots'].median():.4f}")
print(f"    Max sl_xg_all_shots: {non_scoring_shots['sl_xg_all_shots'].max():.4f}")

# Show examples of high-xG shots that didn't score
high_xg_misses = non_scoring_shots[non_scoring_shots['sl_xg_all_shots'] > 0.3].sort_values('sl_xg_all_shots', ascending=False).head(5)
print(f"\nHIGH-XG SHOTS THAT DIDN'T SCORE (Top 5):")
display_cols = ['game_id', 'sequence_id', 'event_type', 'outcome', 'sl_xg_all_shots', 'target_xg', 
                'x_adj', 'y_adj', 'distance_to_net_event', 'angle_to_net_event']
print(high_xg_misses[display_cols].to_string())

# Show examples of scoring shots
scoring_examples = scoring_shots.sort_values('sl_xg_all_shots', ascending=False).head(5)
print(f"\nSCORING SHOTS (Top 5 by sl_xg_all_shots):")
print(scoring_examples[display_cols].to_string())

print("=" * 80)

COMPARING target_xg WITH sl_xg_all_shots

SHOT/DEFLECTION EVENTS:
  Total: 55,999
  With sl_xg_all_shots: 53,961 (96.36%)
  Scoring shots (target_xg=1): 2,810

sl_xg_all_shots COMPARISON:
  Scoring shots (target_xg=1):
    Mean sl_xg_all_shots: 0.2051
    Median sl_xg_all_shots: 0.1451
    Max sl_xg_all_shots: 0.9384
  Non-scoring shots (target_xg=0):
    Mean sl_xg_all_shots: 0.0431
    Median sl_xg_all_shots: 0.0157
    Max sl_xg_all_shots: 0.8141

HIGH-XG SHOTS THAT DIDN'T SCORE (Top 5):
                                      game_id  sequence_id event_type     outcome  sl_xg_all_shots  target_xg      x_adj      y_adj  distance_to_net_event  angle_to_net_event
1573619  f4842ff6-4e11-a003-f74b-261a8b15152d           53       shot      failed         0.814125          0 -60.558760  40.481266             154.940490            0.264337
1039246  ad08e19e-7a2f-4217-d04e-81bd88bb827c           32       shot  successful         0.747541          0  86.810900   1.258823               2.525232

### Create Counterfactual Outcome Column for xG Model

**Rationale**: The xG model is counterfactual — it predicts shot quality based on positioning, defensive pressure, and pre-shot context, **regardless of whether the shot was on-net or missed wide**.

For shots and deflections, we mask (set to NaN) the outcome column so the model can't "cheat" by using whether the shot was on-net.

For all other events, we preserve the outcome to provide additional context (pass was completed/incomplete, block was successful/failed, etc.).

**Result**: 
- Create `outcome_xg` column with outcome masked for shots/deflections
- Keep original `outcome` column intact for Optimus Reim (Phase 5)

In [17]:
print("=" * 80)
print("CREATING COUNTERFACTUAL OUTCOME COLUMN (outcome_xg)")
print("=" * 80)

# Initialize outcome_xg as a copy of outcome
df_events['outcome_xg'] = df_events['outcome'].copy()

# Identify shots and deflections
shot_deflection_mask = df_events['event_type'].isin(['shot', 'deflection'])

# Mask outcome for shots/deflections (set to NaN)
df_events.loc[shot_deflection_mask, 'outcome_xg'] = np.nan

print(f"\nOUTCOME_XG COLUMN:")
print(f"  Masked events (shots/deflections): {shot_deflection_mask.sum():,}")
print(f"  Preserved events (all others): {(~shot_deflection_mask).sum():,}")

print(f"\nOUTCOME_XG VALUE COUNTS (non-null):")
print(df_events[df_events['event_type'] != 'shot']['outcome_xg'].value_counts().head())

print(f"\nSAMPLE ROWS:")
print("Shots/Deflections (outcome_xg should be NaN):")
shot_sample = df_events[shot_deflection_mask][['event_type', 'outcome', 'outcome_xg']].head(3)
print(shot_sample.to_string())

print(f"\nOther Events (outcome_xg should match outcome):")
other_sample = df_events[~shot_deflection_mask][['event_type', 'outcome', 'outcome_xg']].head(3)
print(other_sample.to_string())

print(f"\n✓ Created outcome_xg column (counterfactual for xG model)")
print(f"  Model A & B will use 'outcome_xg' instead of 'outcome' for shots/deflections")
print(f"  Opimus Reim (Phase 5) will use original 'outcome' column")
print("=" * 80)

CREATING COUNTERFACTUAL OUTCOME COLUMN (outcome_xg)

OUTCOME_XG COLUMN:
  Masked events (shots/deflections): 55,999
  Preserved events (all others): 1,602,413

OUTCOME_XG VALUE COUNTS (non-null):
outcome_xg
successful      1186796
failed           298781
undetermined      91582
Name: count, dtype: int64

SAMPLE ROWS:
Shots/Deflections (outcome_xg should be NaN):
    event_type     outcome outcome_xg
94        shot  successful        NaN
103       shot      failed        NaN
112       shot  successful        NaN

Other Events (outcome_xg should match outcome):
  event_type     outcome  outcome_xg
0    faceoff      failed      failed
1    faceoff  successful  successful
2        lpr  successful  successful

✓ Created outcome_xg column (counterfactual for xG model)
  Model A & B will use 'outcome_xg' instead of 'outcome' for shots/deflections
  Opimus Reim (Phase 5) will use original 'outcome' column


In [18]:
print("=" * 80)
print("ENCODING outcome_xg COLUMN")
print("=" * 80)

# Create outcome_xg_id using the same vocabulary as outcome_id
# This allows the model to distinguish between masking (NaN → 0 padding token) and actual outcome values

df_events['outcome_xg_id'] = df_events['outcome_xg'].map(
    lambda x: vocabs['outcome'].get(x, vocabs['outcome'].get('<UNK>', 1)) if pd.notna(x) else 0
)

print(f"\nOUTCOME_XG_ID ENCODING:")
print(f"  Padding token (0) used for masked shots/deflections: {(df_events['outcome_xg_id'] == 0).sum():,}")
print(f"  Actual outcome tokens: {(df_events['outcome_xg_id'] > 0).sum():,}")

print(f"\nOUTCOME_XG_ID VALUE COUNTS:")
print(df_events['outcome_xg_id'].value_counts().sort_index().head(10))

print(f"\nVERIFICATION:")
print("Sample shots (should have outcome_xg_id=0):")
shot_sample_check = df_events[shot_deflection_mask][['event_type', 'outcome', 'outcome_xg', 'outcome_id', 'outcome_xg_id']].head(3)
print(shot_sample_check.to_string())

print("\nSample other events (should have matching outcome_id and outcome_xg_id):")
other_sample_check = df_events[~shot_deflection_mask][['event_type', 'outcome', 'outcome_xg', 'outcome_id', 'outcome_xg_id']].head(3)
print(other_sample_check.to_string())

print(f"\n✓ Created outcome_xg_id for xG model training")
print("=" * 80)

ENCODING outcome_xg COLUMN

OUTCOME_XG_ID ENCODING:
  Padding token (0) used for masked shots/deflections: 81,253
  Actual outcome tokens: 1,577,159

OUTCOME_XG_ID VALUE COUNTS:
outcome_xg_id
0      81253
2     298781
3    1186796
4      91582
Name: count, dtype: int64

VERIFICATION:
Sample shots (should have outcome_xg_id=0):
    event_type     outcome outcome_xg  outcome_id  outcome_xg_id
94        shot  successful        NaN           3              0
103       shot      failed        NaN           2              0
112       shot  successful        NaN           3              0

Sample other events (should have matching outcome_id and outcome_xg_id):
  event_type     outcome  outcome_xg  outcome_id  outcome_xg_id
0    faceoff      failed      failed           2              2
1    faceoff  successful  successful           3              3
2        lpr  successful  successful           3              3

✓ Created outcome_xg_id for xG model training


In [19]:
# Context-aware post-whistle continuity audit (aligned with Phase 1 policy)
print("=== Post-Whistle Continuity Audit ===")

whistle_events = df_events[df_events['event_type'] == 'whistle'].copy()
if len(whistle_events) > 0:
    whistle_idx = whistle_events.index.to_numpy()
    next_idx = whistle_idx + 1
    valid = next_idx < len(df_events)

    whistle_idx = whistle_idx[valid]
    next_idx = next_idx[valid]

    whistle_rows = df_events.loc[whistle_idx]
    next_rows = df_events.loc[next_idx]

    same_seq = (
        (whistle_rows['game_id'].values == next_rows['game_id'].values)
        & (whistle_rows['sequence_id'].values == next_rows['sequence_id'].values)
    )

    next_has_player = next_rows['player_id'].notna().values if 'player_id' in next_rows.columns else np.zeros(len(next_rows), dtype=bool)
    allowed_post_whistle = np.isin(next_rows['event_type'].values, ['penalty', 'penaltydrawn']) & next_has_player

    unexpected_same_seq = same_seq & (~allowed_post_whistle)

    print(f"Whistles checked: {len(whistle_events):,}")
    print(f"Same-sequence continuations: {same_seq.sum():,}")
    print(f"Allowed post-whistle penalty continuations: {(same_seq & allowed_post_whistle).sum():,}")

    if unexpected_same_seq.sum() == 0:
        print("✓ No unexpected same-sequence post-whistle continuations found.")
    else:
        print(f"⚠ Warning: {unexpected_same_seq.sum():,} unexpected same-sequence post-whistle continuations")
        bad_idx = next_idx[unexpected_same_seq]
        show_cols = ['game_id', 'period', 'sequence_id', 'sequence_event_id', 'event_type', 'player_id', 'period_time']
        show_cols = [c for c in show_cols if c in df_events.columns]
        print(df_events.loc[bad_idx, show_cols].head(20).to_string(index=False))
else:
    print("✓ No whistle events found in dataset.")

=== Post-Whistle Continuity Audit ===
Whistles checked: 25,517
Same-sequence continuations: 244
Allowed post-whistle penalty continuations: 244
✓ No unexpected same-sequence post-whistle continuations found.


In [20]:
# Define metadata columns (for analysis, not model input)
# These are identifiers and human-readable strings NOT used as model features
# Note: Avoid duplicates with CONTINUOUS_EVENT_FEATURES and CATEGORICAL_FEATURES
METADATA_COLS = [
    'game_id',
    'sequence_id',
    'sl_event_id',
    'sequence_event_id',
    'game_event_id',
    'period',
    'event_type',
    'outcome',
    'player_id',
    'team_id',
    'description_clean',
    'flags_clean',
    'embedding_text_clean',
    'sl_xg_all_shots',        # Sportlogiq's xG (for comparison with our Transformer xG)
    'target_xg',              # Binary label for xG model (1 = scoring shot, 0 = non-scoring)
    'outcome_xg',             # Counterfactual outcome for xG model (NaN for shots/deflections)
    'outcome_xg_id',          # Encoded outcome_xg (0=padding for masked, 1+=actual outcomes)
    'horizon_end_time',       # Dynamic target horizon end within period
    'sec_next_stoppage'       # Seconds to next whistle/goal/end_of_period
]

# Define encoded categorical columns (will be integer embedded in model)
CATEGORICAL_ENCODED = [f'{feat}_id' for feat in CATEGORICAL_FEATURES]

# Text embedding index (maps to text_embeddings.npy)
TEXT_EMBEDDING_COLS = ['text_embedding_idx']

# Binary features (includes EOS token)
BINARY_FEATURES_FINAL = BINARY_EVENT_FEATURES + ['is_eos']

# Create final column list
FINAL_COLS = (
    METADATA_COLS +
    CATEGORICAL_ENCODED +
    TEXT_EMBEDDING_COLS +
    CONTINUOUS_EVENT_FEATURES +
    BINARY_FEATURES_FINAL +
    TRACKING_FEATURES +
    ['target']
)

# Verify all columns exist and are unique
missing_final = [col for col in FINAL_COLS if col not in df_events.columns]
if missing_final:
    print(f"❌ Missing columns for final dataset: {missing_final}")
    print(f"\nAvailable columns matching pattern:")
    for col in missing_final:
        pattern = col.split('_')[0]
        matches = [c for c in df_events.columns if pattern in c]
        print(f"  {col}: {matches[:5]}")
else:
    print(f"✓ All required columns present")

# Check for duplicates
duplicates = [col for col in FINAL_COLS if FINAL_COLS.count(col) > 1]
if duplicates:
    print(f"\n❌ ERROR: Duplicate columns found: {set(duplicates)}")
    print(f"   This will cause parquet save to fail!")
else:
    print(f"✓ No duplicate columns")

# Select final columns
df_final = df_events[FINAL_COLS].copy()

print(f"\n{'='*80}")
print(f"FINAL DATASET STRUCTURE")
print(f"{'='*80}")

print(f"\nDataset shape: {df_final.shape}")
print(f"  Events: {len(df_final):,}")
print(f"  Columns: {len(FINAL_COLS)}")

print(f"\nColumn breakdown:")
print(f"  Metadata (not for model): {len(METADATA_COLS)}")
print(f"  Categorical (encoded): {len(CATEGORICAL_ENCODED)}")
print(f"  Text embedding index: {len(TEXT_EMBEDDING_COLS)}")
print(f"  Continuous event: {len(CONTINUOUS_EVENT_FEATURES)}")
print(f"  Binary features: {len(BINARY_FEATURES_FINAL)}")
print(f"  Tracking: {len(TRACKING_FEATURES)}")
print(f"  Target: 1")

print(f"\nModel input dimensions:")
print(f"  Categorical tokens: {len(CATEGORICAL_ENCODED)} (will be embedded)")
print(f"  Text embeddings: 384-dim (pre-computed)")
print(f"  Continuous features: {len(CONTINUOUS_EVENT_FEATURES)}")
print(f"  Binary features: {len(BINARY_FEATURES_FINAL)}")
print(f"  Tracking features: {len(TRACKING_FEATURES)}")
print(f"  Total event features: {len(CONTINUOUS_EVENT_FEATURES) + len(BINARY_FEATURES_FINAL)}")

print(f"\nSample of final dataset:")
print(df_final.head())

✓ All required columns present
✓ No duplicate columns

FINAL DATASET STRUCTURE

Dataset shape: (1658412, 111)
  Events: 1,658,412
  Columns: 111

Column breakdown:
  Metadata (not for model): 19
  Categorical (encoded): 3
  Text embedding index: 1
  Continuous event: 11
  Binary features: 4
  Tracking: 72
  Target: 1

Model input dimensions:
  Categorical tokens: 3 (will be embedded)
  Text embeddings: 384-dim (pre-computed)
  Continuous features: 11
  Binary features: 4
  Tracking features: 72
  Total event features: 15

Sample of final dataset:
                                game_id  sequence_id  sl_event_id  \
0  00b0366a-95c6-5250-2dae-e3dd5c4198bc            1            1   
1  00b0366a-95c6-5250-2dae-e3dd5c4198bc            1            2   
2  00b0366a-95c6-5250-2dae-e3dd5c4198bc            1            3   
3  00b0366a-95c6-5250-2dae-e3dd5c4198bc            1            4   
4  00b0366a-95c6-5250-2dae-e3dd5c4198bc            1            5   

   sequence_event_id  game_event

## Prepare Final Dataset: Two Models, Two Feature Sets

**Overview**: The final `tensor_ready_dataset.parquet` includes all columns needed for both Phase 4 (xG) and Phase 5 (Optimus Reim):

| Column | Phase 4 (xG) | Phase 5 (Optimus Reim) | Purpose |
|--------|------|----------|---------|
| `outcome_id` | ❌ Do NOT use | ✅ Use | Original outcome (relevant for net impact) |
| `outcome_xg_id` | ✅ Use | ❌ Do NOT use | Counterfactual outcome (masked for shots/deflections) |
| `target_xg` | ✅ Use | ❌ Do NOT use | Binary label (is goal) |
| `target` | ❌ Do NOT use | ✅ Use | 3-class actor-relative label |

**Key Distinction**:
- **Phase 4 (xG)**: Build dataset with `outcome_xg_id` as outcome feature, train on `target_xg` (binary goal prediction)
- **Phase 5 (Optimus Reim)**: Build dataset with `outcome_id` as outcome feature, train on `target` (3-class net impact)

In [21]:
import json

# Create output directory if needed
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Save vocabularies
vocab_path = OUTPUT_DIR / "vocabularies.json"

# Convert vocabs to serializable format
vocab_export = {}
for feature, vocab in vocabs.items():
    # Convert to string keys for JSON compatibility
    vocab_export[feature] = {str(k): int(v) for k, v in vocab.items()}

with open(vocab_path, 'w') as f:
    json.dump(vocab_export, f, indent=2)

print(f"✓ Saved vocabularies to: {vocab_path}")
print(f"\nVocabulary sizes:")
for feature, vocab in vocabs.items():
    print(f"  {feature}: {len(vocab)} (including <PAD>)")

✓ Saved vocabularies to: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\vocabularies.json

Vocabulary sizes:
  event_type: 26 (including <PAD>)
  outcome: 5 (including <PAD>)
  period: 6 (including <PAD>)


In [22]:
# Save final dataset
final_dataset_path = OUTPUT_DIR / "tensor_ready_dataset.parquet"
df_final.to_parquet(final_dataset_path, index=False)

print(f"✓ Saved final dataset to: {final_dataset_path}")
print(f"  Shape: {df_final.shape}")
print(f"  Size: {final_dataset_path.stat().st_size / 1024 / 1024:.2f} MB")

# Save feature column definitions with detailed structure
feature_definitions = {
    'metadata_columns': METADATA_COLS,
    'categorical_features': {
        'columns': CATEGORICAL_ENCODED,
        'original_features': CATEGORICAL_FEATURES,
        'vocab_sizes': {feat: len(vocabs[feat]) for feat in CATEGORICAL_FEATURES}
    },
    'text_embeddings': {
        'columns': TEXT_EMBEDDING_COLS,
        'embedding_file': 'text_embeddings.npy',
        'dimension': 384,
        'model': 'all-MiniLM-L6-v2',
        'normalized': True,
        'source_features': TEXT_FEATURES
    },
    'continuous_event_features': {
        'columns': CONTINUOUS_EVENT_FEATURES,
        'raw_features': CONTINUOUS_EVENT_FEATURES_RAW,
        'possession_relative': CONTINUOUS_POSSESSION_FEATURES
    },
    'binary_features': {
        'columns': BINARY_FEATURES_FINAL,
        'possession_relative': BINARY_EVENT_FEATURES,
        'eos_token': ['is_eos']
    },
    'tracking_features': {
        'columns': TRACKING_FEATURES,
        'actor_features': ACTOR_FEATURES,
        'teammate_features': TEAMMATE_FEATURES,
        'opponent_features': OPPONENT_FEATURES,
        'total_dim': len(TRACKING_FEATURES)
    },
    'target_column': 'target',
    'target_classes': {
        0: 'Possession Goal',
        1: 'Defending Goal',
        2: 'No Goal'
    },
    'dimensions': {
        'categorical_tokens': len(CATEGORICAL_ENCODED),
        'text_embedding': 384,
        'continuous_event': len(CONTINUOUS_EVENT_FEATURES),
        'binary': len(BINARY_FEATURES_FINAL),
        'tracking': len(TRACKING_FEATURES),
        'total_event_features': len(CONTINUOUS_EVENT_FEATURES) + len(BINARY_FEATURES_FINAL),
        'total_features_excluding_text': len(CONTINUOUS_EVENT_FEATURES) + len(BINARY_FEATURES_FINAL) + len(TRACKING_FEATURES)
    },
    'model_architecture': {
        'input_branches': [
            'Event MLP (continuous + binary)',
            'Tracking projection (72-dim)',
            'Text projection (384-dim)',
            'Categorical embeddings (event_type, outcome, period)'
        ],
        'fusion': 'Concat + Linear projection',
        'encoder': 'Transformer encoder',
        'output_head': '3-layer MLP with LayerNorm (d_model → 512 → 256 → 3)'
    }
}

feature_def_path = OUTPUT_DIR / "feature_definitions.json"
with open(feature_def_path, 'w') as f:
    json.dump(feature_definitions, f, indent=2)

print(f"\n✓ Saved feature definitions to: {feature_def_path}")

#Load text embeddings and save as .npy
text_embeddings_path = OUTPUT_DIR / "text_embeddings.npy"
unique_texts = df_events['embedding_text_clean'].unique()

print(f"\n{'='*80}")
print(f"SAVED FILES:")
print(f"{'='*80}")
print(f"  1. {final_dataset_path.name} ({df_final.shape[0]:,} events)")
print(f"  2. text_embeddings.npy ({len(unique_texts):,} unique, 384-dim)")
print(f"  3. vocabularies.json ({len(vocabs)} categorical features)")
print(f"  4. feature_definitions.json (complete schema)")

✓ Saved final dataset to: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\tensor_ready_dataset.parquet
  Shape: (1658412, 111)
  Size: 334.24 MB

✓ Saved feature definitions to: x:\My Files\Python\Sports Analytics Projects\Hockey\HALO\Tensor-Ready Data\Final Datasets\feature_definitions.json

SAVED FILES:
  1. tensor_ready_dataset.parquet (1,658,412 events)
  2. text_embeddings.npy (2,539 unique, 384-dim)
  3. vocabularies.json (3 categorical features)
  4. feature_definitions.json (complete schema)


In [23]:
print("=" * 80)
print("PHASE 3: TENSOR-READY DATASET - FINAL SUMMARY")
print("=" * 80)

print(f"\n📊 DATASET STATISTICS:")
print(f"  Total events: {len(df_final):,}")
print(f"  Total sequences: {df_final.groupby(['game_id', 'sequence_id']).ngroups:,}")
print(f"  Total games: {df_final['game_id'].nunique():,}")

print(f"\n🎯 TARGET DISTRIBUTION (Actor-Relative):")
target_counts = df_final['target'].value_counts().sort_index()
target_pcts = df_final['target'].value_counts(normalize=True).sort_index() * 100
for target_class, count in target_counts.items():
    class_name = feature_definitions['target_classes'][target_class]
    pct = target_pcts[target_class]
    print(f"  Class {target_class} ({class_name}): {count:,} ({pct:.2f}%)")

print(f"\n  ℹ️  Note: Targets are actor-relative (labeled from each event's team perspective)")
print(f"     When possession changes within a sequence, targets change accordingly.")

print(f"\n📏 SEQUENCE STATISTICS:")
seq_lengths = df_final.groupby(['game_id', 'sequence_id']).size()
print(f"  Mean length: {seq_lengths.mean():.1f} events")
print(f"  Median length: {seq_lengths.median():.0f} events")
print(f"  Max length: {seq_lengths.max()} events")
print(f"  Min length: {seq_lengths.min()} events")
print(f"  Std dev: {seq_lengths.std():.1f} events")
print(f"\n  Sequences > 100 events: {(seq_lengths > 100).sum():,} ({(seq_lengths > 100).mean()*100:.1f}%)")
print(f"  Sequences > 128 events: {(seq_lengths > 128).sum():,} ({(seq_lengths > 128).mean()*100:.1f}%)")
print(f"  Sequences > 256 events: {(seq_lengths > 256).sum():,} ({(seq_lengths > 256).mean()*100:.1f}%)")

print(f"\n🔢 FEATURE DIMENSIONS:")
print(f"\n  Categorical features (integer-embedded in model):")
for feat in CATEGORICAL_FEATURES:
    vocab_size = len(vocabs[feat])
    encoded_col = f'{feat}_id'
    print(f"    {feat:15s} → {encoded_col:20s} (vocab={vocab_size})")

print(f"\n  Text embeddings (pre-computed SentenceTransformer):")
print(f"    Model: all-MiniLM-L6-v2")
print(f"    Dimension: 384")
print(f"    Unique texts: {len(unique_texts):,}")
print(f"    Normalized: Yes (L2)")
print(f"    Source: description_clean + flags")

print(f"\n  Continuous features: {len(CONTINUOUS_EVENT_FEATURES)}")
for feat in CONTINUOUS_EVENT_FEATURES:
    print(f"    - {feat}")

print(f"\n  Binary features: {len(BINARY_FEATURES_FINAL)}")
for feat in BINARY_FEATURES_FINAL:
    print(f"    - {feat}")

print(f"\n  Tracking features: {len(TRACKING_FEATURES)}")
print(f"    - Actor: {len(ACTOR_FEATURES)}")
print(f"    - Teammates: {len(TEAMMATE_FEATURES)} (5 players × 6 features)")
print(f"    - Opponents: {len(OPPONENT_FEATURES)} (6 players × 6 features)")

print(f"\n🏗️  MODEL ARCHITECTURE:")
print(f"  Input branches:")
print(f"    1. Event MLP: {len(CONTINUOUS_EVENT_FEATURES) + len(BINARY_FEATURES_FINAL)} features (continuous + binary)")
print(f"    2. Tracking projection: {len(TRACKING_FEATURES)} features")
print(f"    3. Text projection: 384-dim (pre-embedded)")
print(f"    4. Categorical embeddings: {len(CATEGORICAL_FEATURES)} tokens")
print(f"\n  Fusion: Concat all branches → Linear(total_dim, d_model)")
print(f"  Encoder: Transformer with positional encoding")
print(f"  Output head: 3-layer MLP with LayerNorm")
print(f"    - Layer 1: d_model → 512 (ReLU + Dropout)")
print(f"    - Layer 2: 512 → 256 (ReLU + Dropout)")
print(f"    - Layer 3: 256 → 3 (logits)")

print(f"\n💾 OUTPUT FILES:")
print(f"  ✓ tensor_ready_dataset.parquet ({df_final.shape[0]:,} events, {df_final.shape[1]} columns)")
print(f"  ✓ text_embeddings.npy ({len(unique_texts):,} unique texts, 384-dim)")
print(f"  ✓ vocabularies.json ({len(vocabs)} categorical features)")
print(f"  ✓ feature_definitions.json (complete schema)")

print(f"\n🚀 READY FOR TRANSFORMER TRAINING:")
print(f"  Actor-relative targets: Each event labeled from its team's perspective")
print(f"  Possession-relative features: All features transformed relative to team_id")
print(f"  Token-level prediction: Each event gets probability distribution over 3 classes")
print(f"  Dual-model strategy: Train baseline (events) vs tracking (events+tracking)")
print(f"\n  Sequence windowing strategy:")
print(f"    - For sequences > 128 events: Take LAST 128 events (closest to outcome)")
print(f"    - Rationale: Events near the goal/whistle are most predictive")
print(f"    - Keeps terminator (goal/whistle) in context")
print(f"    - Uniform tensor shape for efficient B580 batching")
print(f"\n  Temporal supervision considerations:")
print(f"    - All events in window share same sequence-level target (actor-relative)")
print(f"    - Early events (t=0-50) have noisier relationship to outcome than late events (t=100-128)")
print(f"    - Recommendation: Use temporally-weighted loss or attend to position encodings")
print(f"    - Alternative: Weight later timesteps more heavily in loss calculation")

print(f"\n  Recommended hyperparameters:")
print(f"    - max_seq_length: 128 (covers {(seq_lengths <= 128).mean()*100:.1f}% fully, remainder windowed)")
print(f"    - batch_size: 16-32 (depends on GPU memory)")
print(f"    - d_model: 256-512")
print(f"    - learning_rate: 1e-4 to 5e-4 (with warmup)")
print(f"    - dropout: 0.1-0.2")

print(f"\n🎮 INTEL GPU (XPU) READY:")
print(f"  Device detection: torch.xpu.is_available()")
print(f"  Optimization: ipex.optimize(model, optimizer)")
print(f"  Text embeddings already computed on XPU")
print(f"  Expected performance: ~2-4x faster than CPU for transformer training")

print("\n" + "=" * 80)
print("PHASE 3 DATASET PREPARATION COMPLETE!")
print("=" * 80)
print(f"\nNext steps:")
print(f"  1. Load dataset: pd.read_parquet('tensor_ready_dataset.parquet')")
print(f"  2. Load embeddings: np.load('text_embeddings.npy')")
print(f"  3. Create PyTorch Dataset class with:")
print(f"     - Sequence windowing (last 128 events)")
print(f"     - Padding for sequences < 128")
print(f"     - Attention masking for padded positions")
print(f"  4. Implement HockeyNetImpactModel with 4-branch architecture")
print(f"  5. Train with actor-relative supervision + temporal loss weighting")
print(f"  6. Evaluate dual-model (baseline vs tracking) on held-out games")
print(f"  7. Analyze per-timestep predictions to validate temporal patterns")
print("=" * 80)

PHASE 3: TENSOR-READY DATASET - FINAL SUMMARY

📊 DATASET STATISTICS:
  Total events: 1,658,412
  Total sequences: 28,095
  Total games: 480

🎯 TARGET DISTRIBUTION (Actor-Relative):
  Class 0 (Possession Goal): 41,418 (2.50%)
  Class 1 (Defending Goal): 22,201 (1.34%)
  Class 2 (No Goal): 1,594,793 (96.16%)

  ℹ️  Note: Targets are actor-relative (labeled from each event's team perspective)
     When possession changes within a sequence, targets change accordingly.

📏 SEQUENCE STATISTICS:
  Mean length: 59.0 events
  Median length: 45 events
  Max length: 508 events
  Min length: 4 events
  Std dev: 50.5 events

  Sequences > 100 events: 4,580 (16.3%)
  Sequences > 128 events: 2,545 (9.1%)
  Sequences > 256 events: 215 (0.8%)

🔢 FEATURE DIMENSIONS:

  Categorical features (integer-embedded in model):
    event_type      → event_type_id        (vocab=26)
    outcome         → outcome_id           (vocab=5)
    period          → period_id            (vocab=6)

  Text embeddings (pre-compu

### Dataset Summary & Statistics

### Save Final Tensor-Ready Dataset

### Save Vocabularies

Save the categorical feature vocabularies for use during training.

### Prepare Final Dataset Structure

Structure the data for both Phase 4 (xG) and Phase 5 (Optimus Reim) models:
- **Metadata columns**: game_id, sequence_id, sl_event_id, player_id, team_id, sl_xg_all_shots, target_xg, outcome_xg, outcome_xg_id (for analysis and xG model)
- **Categorical features (encoded)**: event_type_id, outcome_id (for net impact model), outcome_xg_id (for xG model), period_id (will be integer-embedded)
- **Text embedding index**: Maps to pre-computed 384-dim embeddings from text_embeddings.npy
- **Continuous event features**: x_adj, y_adj, period_time_remaining, score_differential_poss, etc. (possession-relative)
- **Binary features**: home_team_poss, net_empty_poss, net_empty_def, is_eos
- **Tracking features**: 72-dimensional vector (actor + teammates + opponents)
- **Targets**: 
  - `target_xg`: Binary (0/1) for Phase 4 xG model
  - `target`: 3-class actor-relative for Phase 5 Optimus Reim model

### Create Actor-Relative Targets (Dynamic Horizon, Vectorized)

Three-class classification where each event is labeled relative to its own team_id using a dynamic, stoppage-aware horizon:
- Class 0 (Possession Goal): Earliest future goal in horizon is by event team
- Class 1 (Defending Goal): Earliest future goal in horizon is by opposing team
- Class 2 (No Goal): No goal in dynamic horizon

Dynamic horizon rules:
- Standard events: period_time + 20s
- Penalties: next faceoff + 120s (single default window for all penalties)
- Capped at period boundary to prevent intermission bleed
- sec_next_stoppage stores seconds to next whistle/goal/end_of_period

Earliest-goal priority guarantees mutual exclusivity (no event can be both Class 0 and Class 1).

### Build Vocabularies for Categorical Features

Create integer encodings for event_type, outcome, and period. Reserve 0 for padding token, 1 for unknown.